/**
 * Mock graph data — used when Neo4j is unavailable.
 * Shape matches what neo4j.js returns so components are driver-agnostic.
 */

export const mockNodes = [
  {
    id: 'person-001',
    label: 'Person',
    name: 'Alice Chen',
    role: 'CEO & Co-Founder',
    company: 'Acme AI',
    composite_score: 8.4,
    founder_likelihood: 9.5,
    pedigree_score: 9.0,
    trajectory_score: 8.5,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/alicechen-example',
    github_handle: 'alicechen-ml',
    bio: 'ML researcher specializing in graph neural networks. Former MIT PhD. Co-founder of Acme AI.',
    manually_reviewed: true,
    review_notes: 'Strong signal: MIT PhD, published at NeurIPS, actively founding.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Machine Learning',
  },
  {
    id: 'person-002',
    label: 'Person',
    name: 'Bob Okafor',
    role: 'Staff Engineer',
    company: 'FinEdge',
    composite_score: 5.8,
    founder_likelihood: 5.5,
    pedigree_score: 7.5,
    trajectory_score: 7.0,
    publication_score: 2.0,
    data_confidence: 7.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/bobokafor-example',
    github_handle: 'bokafor',
    bio: 'Staff engineer at a Series B fintech. Oxford CS graduate. Open-source contributor.',
    manually_reviewed: true,
    review_notes: 'Good trajectory, but no founding history yet. Watch for job changes.',
    geo: 'London',
    degree: 'BS',
    field: 'Computer Science',
  },
  {
    id: 'person-003',
    label: 'Person',
    name: 'Sara Müller',
    role: 'Associate Professor',
    company: 'MIT',
    composite_score: 8.0,
    founder_likelihood: 7.0,
    pedigree_score: 9.5,
    trajectory_score: 8.0,
    publication_score: 9.0,
    data_confidence: 6.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/saramuller-example',
    github_handle: null,
    bio: 'Associate Professor of Computational Biology at MIT. Multiple patents. Advising Acme AI.',
    manually_reviewed: true,
    review_notes: 'Academic star with IP. Likely to spin out in 2–3 years.',
    geo: 'Bay Area',
    degree: 'Faculty',
    field: 'Computational Biology',
  },
  {
    id: 'person-004',
    label: 'Person',
    name: 'James Park',
    role: 'Principal Engineer',
    company: 'DeepScale',
    composite_score: 7.1,
    founder_likelihood: 7.8,
    pedigree_score: 8.0,
    trajectory_score: 7.5,
    publication_score: 4.0,
    data_confidence: 7.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/jamespark-example',
    github_handle: 'jpark-eng',
    bio: 'Principal engineer at a stealth ML infra startup. Stanford MS. Ex-Google Brain.',
    manually_reviewed: true,
    review_notes: 'Ex-Google Brain signal is strong. Recently went stealth — watch closely.',
    geo: 'Bay Area',
    degree: 'MS',
    field: 'Computer Science',
  },
  {
    id: 'person-005',
    label: 'Person',
    name: 'Priya Nair',
    role: 'Postdoctoral Researcher',
    company: 'Stanford',
    composite_score: 7.6,
    founder_likelihood: 6.5,
    pedigree_score: 9.0,
    trajectory_score: 6.5,
    publication_score: 8.5,
    data_confidence: 6.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/priyanair-example',
    github_handle: 'priya-ml',
    bio: 'Postdoc at Stanford AI Lab. Published 12 papers on diffusion models. Filed 2 patents.',
    manually_reviewed: false,
    review_notes: '',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Artificial Intelligence',
  },
  {
    id: 'person-006',
    label: 'Person',
    name: 'Carlos Mendez',
    role: 'VP Engineering',
    company: 'Stripe',
    composite_score: 6.9,
    founder_likelihood: 6.0,
    pedigree_score: 8.5,
    trajectory_score: 7.8,
    publication_score: 1.0,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/carlosmendez-example',
    github_handle: 'cmendez',
    bio: 'VP Engineering at Stripe. Previously eng lead at Square. MIT EECS grad.',
    manually_reviewed: true,
    review_notes: 'Classic pre-founder profile. Has angel invested in 3 companies.',
    geo: 'Bay Area',
    degree: 'BS',
    field: 'EECS',
  },
  {
    id: 'inst-001',
    label: 'Institution',
    name: 'MIT',
    type: 'university',
    country: 'USA',
    world_rank: 1,
  },
  {
    id: 'inst-002',
    label: 'Institution',
    name: 'Stanford',
    type: 'university',
    country: 'USA',
    world_rank: 2,
  },
  {
    id: 'inst-003',
    label: 'Institution',
    name: 'Oxford',
    type: 'university',
    country: 'UK',
    world_rank: 3,
  },
  {
    id: 'co-001',
    label: 'Company',
    name: 'Acme AI',
    stage: 'seed',
    sector: 'deeptech',
    hq_city: 'San Francisco',
  },
  {
    id: 'geo-001',
    label: 'GeographicCluster',
    name: 'Bay Area',
    country: 'USA',
  },
  {
    id: 'geo-002',
    label: 'GeographicCluster',
    name: 'London',
    country: 'UK',
  },
]

export const mockEdges = [
  { id: 'e1',  source: 'person-001', target: 'inst-001',   type: 'ALUMNI_OF',        label: 'PhD' },
  { id: 'e2',  source: 'person-002', target: 'inst-003',   type: 'ALUMNI_OF',        label: 'BS' },
  { id: 'e3',  source: 'person-003', target: 'inst-001',   type: 'ALUMNI_OF',        label: 'Faculty' },
  { id: 'e4',  source: 'person-004', target: 'inst-002',   type: 'ALUMNI_OF',        label: 'MS' },
  { id: 'e5',  source: 'person-005', target: 'inst-002',   type: 'ALUMNI_OF',        label: 'PhD' },
  { id: 'e6',  source: 'person-006', target: 'inst-001',   type: 'ALUMNI_OF',        label: 'BS' },
  { id: 'e7',  source: 'person-001', target: 'person-003', type: 'ADVISED_BY',       label: 'PhD advisor' },
  { id: 'e8',  source: 'person-001', target: 'co-001',     type: 'EMPLOYED_AT',      label: 'CEO & Co-Founder' },
  { id: 'e9',  source: 'person-001', target: 'person-003', type: 'CO_AUTHORED_WITH', label: 'NeurIPS 2023' },
  { id: 'e10', source: 'person-001', target: 'geo-001',    type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e11', source: 'person-002', target: 'geo-002',    type: 'LOCATED_IN',       label: 'London' },
  { id: 'e12', source: 'person-003', target: 'geo-001',    type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e13', source: 'person-004', target: 'geo-001',    type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e14', source: 'person-005', target: 'geo-001',    type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e15', source: 'person-006', target: 'geo-001',    type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e16', source: 'person-004', target: 'person-001', type: 'CO_AUTHORED_WITH', label: 'ICML 2022' },
  { id: 'e17', source: 'person-005', target: 'person-003', type: 'CO_AUTHORED_WITH', label: 'Nature 2023' },
]
