/**
 * Mock graph data — AI Researcher rankings (top 49 globally).
 * Shape matches what neo4j.js returns so components are driver-agnostic.
 * Source: AI_Researchers_Rankings.pdf
 */

export const mockNodes = [
  // ── PERSON NODES ──────────────────────────────────────────────────────────

  {
    id: 'person-001',
    label: 'Person',
    name: 'Yann LeCun',
    role: 'VP & Chief AI Scientist',
    company: 'Meta AI / New York University',
    composite_score: 9.8,
    founder_likelihood: 6.5,
    pedigree_score: 9.5,
    trajectory_score: 9.8,
    publication_score: 10.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/yann-lecun',
    github_handle: 'ylecun',
    bio: 'Turing Award laureate (2018). Pioneer of convolutional neural networks (CNNs) and deep learning. Led development of LeNet, foundational to modern image recognition. Chief AI Scientist at Meta and Silver Professor at NYU.',
    manually_reviewed: true,
    review_notes: 'Turing Award winner. CNNs underpin virtually all modern vision AI. Extremely high citation count (~250k). Tier 1 without question.',
    geo: 'New York',
    degree: 'PhD',
    field: 'Deep Learning / Computer Vision',
  },
  {
    id: 'person-002',
    label: 'Person',
    name: 'Geoffrey Hinton',
    role: 'Emeritus Professor',
    company: 'University of Toronto / Google (former)',
    composite_score: 9.9,
    founder_likelihood: 5.0,
    pedigree_score: 10.0,
    trajectory_score: 9.5,
    publication_score: 10.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/geoffrey-hinton',
    github_handle: null,
    bio: 'Turing Award laureate (2018). Widely regarded as the "Godfather of Deep Learning." Pioneered backpropagation, Boltzmann machines, and capsule networks. Left Google in 2023 to speak freely about AI risks.',
    manually_reviewed: true,
    review_notes: 'Turing Award. Co-authored the seminal 1986 backpropagation paper. ~300k citations. Resigned from Google to warn about AI dangers — highest-signal researcher in the field.',
    geo: 'Toronto',
    degree: 'PhD',
    field: 'Deep Learning / Neural Networks',
  },
  {
    id: 'person-003',
    label: 'Person',
    name: 'Yoshua Bengio',
    role: 'Full Professor & Scientific Director',
    company: 'Université de Montréal / Mila',
    composite_score: 9.8,
    founder_likelihood: 6.0,
    pedigree_score: 9.5,
    trajectory_score: 9.7,
    publication_score: 10.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/yoshuabengio',
    github_handle: null,
    bio: 'Turing Award laureate (2018). Pioneer of deep learning and attention mechanisms. Founded Mila, the world\'s largest academic deep learning lab. Leading voice on AI safety and responsible AI governance.',
    manually_reviewed: true,
    review_notes: 'Turing Award. H-index ~170. Co-invented attention mechanisms (precursor to Transformer). Critical AI safety advocate. Montreal ecosystem founder.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'Deep Learning / AI Safety',
  },
  {
    id: 'person-004',
    label: 'Person',
    name: 'Andrew Ng',
    role: 'Founder & CEO',
    company: 'DeepLearning.AI / AI Fund',
    composite_score: 9.5,
    founder_likelihood: 9.8,
    pedigree_score: 9.5,
    trajectory_score: 9.3,
    publication_score: 9.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/andrewyng',
    github_handle: null,
    bio: 'Co-founder of Coursera, Google Brain, and DeepLearning.AI. Former Chief Scientist at Baidu. His online ML courses have educated over 7 million learners globally. Pioneer of large-scale distributed deep learning.',
    manually_reviewed: true,
    review_notes: 'Serial founder: Google Brain, Coursera, DeepLearning.AI, AI Fund. Highest founder_likelihood in cohort. Textbook-level influence on applied ML education.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Machine Learning / Deep Learning',
  },
  {
    id: 'person-005',
    label: 'Person',
    name: 'Fei-Fei Li',
    role: 'Sequoia Professor & Co-Director',
    company: 'Stanford University HAI',
    composite_score: 9.4,
    founder_likelihood: 8.0,
    pedigree_score: 9.5,
    trajectory_score: 9.2,
    publication_score: 9.5,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/fei-fei-li-4541247',
    github_handle: null,
    bio: 'Creator of ImageNet, the dataset that catalyzed the deep learning revolution. Co-Director of Stanford HAI. Former VP at Google and Chief AI Scientist at Google Cloud. Co-founded AI4ALL to increase diversity in AI.',
    manually_reviewed: true,
    review_notes: 'ImageNet single-handedly triggered the deep learning revolution. Co-Director of Stanford HAI. Strong policy influence. Co-founder of AI4ALL and WorldLabs.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Computer Vision / AI for Social Good',
  },
  {
    id: 'person-006',
    label: 'Person',
    name: 'Jürgen Schmidhuber',
    role: 'Scientific Director',
    company: 'IDSIA / KAUST',
    composite_score: 9.0,
    founder_likelihood: 5.5,
    pedigree_score: 9.0,
    trajectory_score: 8.8,
    publication_score: 9.5,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/juergen-schmidhuber',
    github_handle: null,
    bio: 'Inventor of Long Short-Term Memory (LSTM) networks with Sepp Hochreiter. Pioneered recurrent neural networks, self-referential learning, and meta-learning. Director at IDSIA and professor at KAUST.',
    manually_reviewed: true,
    review_notes: 'LSTM inventor — still ubiquitous in sequence modeling. Controversial but highly influential. H-index ~90. Contested credit for multiple DL breakthroughs.',
    geo: 'Lugano',
    degree: 'PhD',
    field: 'Recurrent Networks / Meta-Learning',
  },
  {
    id: 'person-007',
    label: 'Person',
    name: 'Bernhard Schölkopf',
    role: 'Director',
    company: 'Max Planck Institute for Intelligent Systems',
    composite_score: 9.2,
    founder_likelihood: 5.0,
    pedigree_score: 9.5,
    trajectory_score: 9.0,
    publication_score: 9.8,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/bernhard-scholkopf',
    github_handle: null,
    bio: 'Leading expert on kernel methods, support vector machines, and causal inference. Director at MPI Tübingen. Pioneer of causality-based AI reasoning. H-index over 130.',
    manually_reviewed: true,
    review_notes: 'H-index ~130+. Kernel methods and SVM co-inventor. Recent pivot to causal ML is shaping next-gen AI. MPI Tübingen is a top European AI hub.',
    geo: 'Tübingen',
    degree: 'PhD',
    field: 'Kernel Methods / Causality',
  },
  {
    id: 'person-008',
    label: 'Person',
    name: 'Michael I. Jordan',
    role: 'Pehong Chen Distinguished Professor',
    company: 'UC Berkeley',
    composite_score: 9.6,
    founder_likelihood: 5.5,
    pedigree_score: 10.0,
    trajectory_score: 9.2,
    publication_score: 10.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/michael-i-jordan',
    github_handle: null,
    bio: 'Widely considered the most cited researcher in machine learning (~250k citations). Pioneered latent Dirichlet allocation, expectation-maximization, and graphical models. Member of the National Academy of Sciences.',
    manually_reviewed: true,
    review_notes: 'Arguably the most cited ML researcher in history. LDA co-inventor. Exceptional breadth: statistics, optimization, distributed systems, ML theory. Strong policy views on AI hype.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Machine Learning / Statistics',
  },
  {
    id: 'person-009',
    label: 'Person',
    name: 'Demis Hassabis',
    role: 'CEO & Co-Founder',
    company: 'Google DeepMind',
    composite_score: 9.7,
    founder_likelihood: 9.5,
    pedigree_score: 9.5,
    trajectory_score: 9.8,
    publication_score: 9.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/demishassabis',
    github_handle: null,
    bio: 'Nobel Prize in Chemistry (2024) for AlphaFold. Co-founder and CEO of DeepMind (acquired by Google for ~$500M). Led development of AlphaGo, AlphaZero, AlphaFold, and Gemini. Child chess prodigy.',
    manually_reviewed: true,
    review_notes: '2024 Nobel Prize in Chemistry. AlphaFold solved protein folding — one of biology\'s greatest challenges. AlphaGo defeated world Go champion. Company sold to Google for $500M.',
    geo: 'London',
    degree: 'PhD',
    field: 'Reinforcement Learning / Computational Biology',
  },
  {
    id: 'person-010',
    label: 'Person',
    name: 'Jeff Dean',
    role: 'Chief Scientist',
    company: 'Google DeepMind',
    composite_score: 9.3,
    founder_likelihood: 6.0,
    pedigree_score: 9.5,
    trajectory_score: 9.0,
    publication_score: 9.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/jeff-dean-8b212555',
    github_handle: null,
    bio: 'Architect of Google\'s core systems: MapReduce, Bigtable, TensorFlow, Spanner, and Google Brain. Led creation of the TPU. Co-authored seminal papers on large language models including PaLM and Gemini.',
    manually_reviewed: true,
    review_notes: 'TensorFlow, MapReduce, Bigtable co-creator. Led Google Brain for a decade. Infrastructure visionary enabling all of modern ML at scale. Legendary engineer.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'ML Systems / Distributed Computing',
  },
  {
    id: 'person-011',
    label: 'Person',
    name: 'Ian Goodfellow',
    role: 'Distinguished Research Scientist',
    company: 'Apple',
    composite_score: 9.2,
    founder_likelihood: 6.5,
    pedigree_score: 9.5,
    trajectory_score: 9.0,
    publication_score: 9.5,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/ian-goodfellow',
    github_handle: 'goodfeli',
    bio: 'Inventor of Generative Adversarial Networks (GANs) — one of the most cited papers in ML history. Author of the landmark "Deep Learning" textbook with Bengio and Courville. Previously at Google Brain and OpenAI.',
    manually_reviewed: true,
    review_notes: 'GAN paper has ~70k citations. "Deep Learning" textbook is the field\'s bible. Invented GANs in one night after a bar argument. Works at Apple on private AI.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Generative Models / Deep Learning',
  },
  {
    id: 'person-012',
    label: 'Person',
    name: 'Pieter Abbeel',
    role: 'Professor & Co-Founder',
    company: 'UC Berkeley / Covariant AI',
    composite_score: 9.0,
    founder_likelihood: 9.2,
    pedigree_score: 9.5,
    trajectory_score: 9.2,
    publication_score: 8.8,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/pieterabbeel',
    github_handle: 'pabbeel',
    bio: 'Pioneer of robot learning from demonstration and reinforcement learning for robotics. Co-founded Covariant (raised $222M), Gradescope (acquired by Turnitin), and Berkeley OpenArms. Recipient of ACM Prize in Computing.',
    manually_reviewed: true,
    review_notes: 'Serial founder: Covariant ($222M raised), Gradescope (acquired). ACM Prize in Computing. Top robotics + RL researcher. Very high founder_likelihood.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Robotics / Reinforcement Learning',
  },
  {
    id: 'person-013',
    label: 'Person',
    name: 'Ilya Sutskever',
    role: 'Co-Founder',
    company: 'Safe Superintelligence Inc.',
    composite_score: 9.5,
    founder_likelihood: 9.8,
    pedigree_score: 9.5,
    trajectory_score: 9.7,
    publication_score: 9.2,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/ilya-sutskever',
    github_handle: null,
    bio: 'Co-founder and former Chief Scientist of OpenAI. Co-invented AlexNet and Seq2Seq. Initiated the pivot to LLMs that led to GPT and ChatGPT. Co-founded Safe Superintelligence Inc. (SSI) in 2024 after departing OpenAI.',
    manually_reviewed: true,
    review_notes: 'AlexNet, Seq2Seq, GPT co-inventor. Left OpenAI to found SSI focused solely on safe superintelligence. One of the most consequential deep learning researchers alive.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Deep Learning / AI Safety',
  },
  {
    id: 'person-014',
    label: 'Person',
    name: 'Ruslan Salakhutdinov',
    role: 'Professor',
    company: 'Carnegie Mellon University',
    composite_score: 8.9,
    founder_likelihood: 5.5,
    pedigree_score: 9.5,
    trajectory_score: 8.8,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/ruslan-salakhutdinov',
    github_handle: 'rsalakhu',
    bio: 'Pioneer of deep Boltzmann machines and multi-modal deep learning. Former Apple Director of AI Research. Professor at CMU. Known for contributions to probabilistic deep learning and zero-shot learning.',
    manually_reviewed: true,
    review_notes: 'Apple Dir of AI Research (former). Deep Boltzmann Machines pioneer. One of Hinton\'s most prominent students. Strong bridge between academia and industry.',
    geo: 'Pittsburgh',
    degree: 'PhD',
    field: 'Deep Learning / Probabilistic Models',
  },
  {
    id: 'person-015',
    label: 'Person',
    name: 'Percy Liang',
    role: 'Associate Professor & Director',
    company: 'Stanford University / CRFM',
    composite_score: 9.0,
    founder_likelihood: 7.5,
    pedigree_score: 9.5,
    trajectory_score: 9.2,
    publication_score: 8.8,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/percy-liang',
    github_handle: 'percyliang',
    bio: 'Director of Stanford\'s Center for Research on Foundation Models (CRFM). Coined the term "foundation models." Pioneer in NLP, semantic parsing, and AI robustness. Led the HELM benchmarking framework.',
    manually_reviewed: true,
    review_notes: 'Coined "foundation models" — now ubiquitous term. HELM benchmark shapes how the field evaluates LLMs. High policy influence on foundation model governance.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'NLP / Foundation Models',
  },
  {
    id: 'person-016',
    label: 'Person',
    name: 'Christopher Manning',
    role: 'Thomas M. Siebel Professor',
    company: 'Stanford University',
    composite_score: 9.1,
    founder_likelihood: 5.5,
    pedigree_score: 9.5,
    trajectory_score: 8.9,
    publication_score: 9.5,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/christopher-manning',
    github_handle: null,
    bio: 'Leading expert in NLP and computational linguistics. Creator of Stanford CoreNLP, GloVe word embeddings, and Stanford Parser. Author of the influential textbook "Introduction to Information Retrieval." H-index ~120.',
    manually_reviewed: true,
    review_notes: 'GloVe embeddings, Stanford CoreNLP, Stanford NER — infrastructure used by millions. H-index ~120. One of the most cited NLP researchers.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Natural Language Processing',
  },
  {
    id: 'person-017',
    label: 'Person',
    name: 'Zoubin Ghahramani',
    role: 'VP Research & Distinguished Researcher',
    company: 'Google / University of Cambridge',
    composite_score: 9.0,
    founder_likelihood: 6.0,
    pedigree_score: 9.5,
    trajectory_score: 8.8,
    publication_score: 9.5,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/zoubin-ghahramani',
    github_handle: null,
    bio: 'Leading authority on Bayesian machine learning, Gaussian processes, and probabilistic deep learning. Professor at Cambridge and VP Research at Google. Former Chief Scientist at Uber AI.',
    manually_reviewed: true,
    review_notes: 'Bayesian DL pioneer. H-index ~95. Led Cambridge ML group for 15+ years. Influential in probabilistic programming and uncertainty quantification.',
    geo: 'Cambridge UK',
    degree: 'PhD',
    field: 'Bayesian ML / Probabilistic Models',
  },
  {
    id: 'person-018',
    label: 'Person',
    name: 'David Silver',
    role: 'Research Scientist & Professor',
    company: 'Google DeepMind / University College London',
    composite_score: 9.5,
    founder_likelihood: 5.0,
    pedigree_score: 9.5,
    trajectory_score: 9.5,
    publication_score: 9.2,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/david-silver',
    github_handle: null,
    bio: 'Lead researcher on AlphaGo, AlphaZero, and MuZero at DeepMind. Pioneer of deep reinforcement learning combining neural networks with Q-learning. Winner of numerous RL awards including the ACM Prize.',
    manually_reviewed: true,
    review_notes: 'AlphaGo — historic milestone where AI defeated world Go champion Lee Sedol. AlphaZero mastered Chess, Shogi, and Go simultaneously without prior knowledge. Foundational RL researcher.',
    geo: 'London',
    degree: 'PhD',
    field: 'Reinforcement Learning',
  },
  {
    id: 'person-019',
    label: 'Person',
    name: 'Sergey Levine',
    role: 'Associate Professor',
    company: 'UC Berkeley',
    composite_score: 8.8,
    founder_likelihood: 7.5,
    pedigree_score: 9.5,
    trajectory_score: 9.0,
    publication_score: 8.7,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/sergey-levine-berkeley',
    github_handle: null,
    bio: 'Leading researcher in deep reinforcement learning for robotics, offline RL, and imitation learning. Co-leads Berkeley\'s RAIL lab. Known for model-free visuomotor policies and robotic learning from diverse data.',
    manually_reviewed: true,
    review_notes: 'Top robotics RL researcher. RAIL lab produces much of Berkeley\'s robotics output. High collaboration density with Abbeel and Finn. Publication velocity very high.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Robot Learning / Deep RL',
  },
  {
    id: 'person-020',
    label: 'Person',
    name: 'Chelsea Finn',
    role: 'Assistant Professor',
    company: 'Stanford University',
    composite_score: 8.9,
    founder_likelihood: 7.0,
    pedigree_score: 9.5,
    trajectory_score: 9.3,
    publication_score: 8.5,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/chelsea-finn',
    github_handle: 'cbfinn',
    bio: 'Inventor of MAML (Model-Agnostic Meta-Learning), the foundational algorithm for few-shot learning. Forbes 30 Under 30. Assistant Professor at Stanford and Research Scientist at Google Brain. Leading figure in meta-learning.',
    manually_reviewed: true,
    review_notes: 'MAML paper has ~25k citations. Invented meta-learning paradigm used across all of modern few-shot learning. Rapid rise — completed PhD and joined Stanford faculty in her 20s.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Meta-Learning / Robot Learning',
  },
  {
    id: 'person-021',
    label: 'Person',
    name: 'Shakir Mohamed',
    role: 'Research Director',
    company: 'Google DeepMind',
    composite_score: 8.7,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.8,
    publication_score: 8.5,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/shakir-mohamed',
    github_handle: 'shakirm',
    bio: 'Research Director at DeepMind specializing in probabilistic ML, generative models, and AI for global development. Co-leads DeepMind\'s work on ML for scientific discovery. Prominent advocate for diversity in AI.',
    manually_reviewed: true,
    review_notes: 'Key figure in probabilistic deep learning. Strong voice on inclusive and ethical AI. Leads DeepMind Africa programme. Broad impact beyond pure research.',
    geo: 'London',
    degree: 'PhD',
    field: 'Probabilistic ML / Generative Models',
  },
  {
    id: 'person-022',
    label: 'Person',
    name: 'Jitendra Malik',
    role: 'Arthur J. Chick Professor',
    company: 'UC Berkeley / Meta AI',
    composite_score: 9.3,
    founder_likelihood: 4.5,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 9.8,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/jitendra-malik',
    github_handle: null,
    bio: 'Pioneer of computer vision: normalized cuts, object detection, and 3D scene understanding. Member of National Academy of Sciences and Engineering. CVPR Lifetime Achievement Award. H-index over 120.',
    manually_reviewed: true,
    review_notes: 'Legendary computer vision researcher. Normalized cuts, contour detection foundational work. H-index ~120+. Trained a who\'s-who of CV researchers. National Academy member.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Computer Vision',
  },
  {
    id: 'person-023',
    label: 'Person',
    name: 'Stuart Russell',
    role: 'Smith-Zadeh Professor',
    company: 'UC Berkeley',
    composite_score: 9.4,
    founder_likelihood: 5.5,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 9.8,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/stuart-russell',
    github_handle: null,
    bio: 'Co-author of "Artificial Intelligence: A Modern Approach" — the field\'s canonical textbook (used in 135+ countries). Founder of the Center for Human-Compatible AI (CHAI). Leading AI safety researcher and policy advocate.',
    manually_reviewed: true,
    review_notes: '"AIMA" textbook used in 1,500+ universities. CHAI founder. "Human Compatible" book is essential AI safety reading. Testified before U.S. Senate on AI risks. Exceptional policy influence.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'AI Safety / Intelligent Agents',
  },
  {
    id: 'person-024',
    label: 'Person',
    name: 'Richard Sutton',
    role: 'Distinguished Research Scientist',
    company: 'University of Alberta / Google DeepMind',
    composite_score: 9.4,
    founder_likelihood: 4.5,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 9.8,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/richard-sutton',
    github_handle: null,
    bio: 'Father of modern reinforcement learning. Co-author of "Reinforcement Learning: An Introduction" — the definitive RL textbook. Invented TD-learning, actor-critic methods, and temporal difference methods.',
    manually_reviewed: true,
    review_notes: 'RL: An Introduction is the canonical textbook. TD-learning and actor-critic methods foundational to all modern RL including DQN, PPO, SAC. Sutton\'s blog post "The Bitter Lesson" is required reading.',
    geo: 'Edmonton',
    degree: 'PhD',
    field: 'Reinforcement Learning',
  },
  {
    id: 'person-025',
    label: 'Person',
    name: 'Michael Bronstein',
    role: 'DeepMind Professor of AI',
    company: 'University of Oxford / Twitter',
    composite_score: 8.8,
    founder_likelihood: 6.5,
    pedigree_score: 9.0,
    trajectory_score: 9.2,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/mikebronstein',
    github_handle: null,
    bio: 'Pioneer of geometric deep learning — extending deep learning to non-Euclidean data (graphs, manifolds). Co-authored the influential "Geometric Deep Learning" blueprint. DeepMind Professor at Oxford.',
    manually_reviewed: true,
    review_notes: 'Geometric Deep Learning framework is reshaping drug discovery and molecular modeling. Strong industry ties. Published influential textbook-style proto-book on GDL.',
    geo: 'Oxford',
    degree: 'PhD',
    field: 'Geometric Deep Learning / Graph Neural Networks',
  },
  {
    id: 'person-026',
    label: 'Person',
    name: 'Max Welling',
    role: 'Research VP & Professor',
    company: 'Microsoft Research / University of Amsterdam',
    composite_score: 8.8,
    founder_likelihood: 6.0,
    pedigree_score: 9.0,
    trajectory_score: 8.8,
    publication_score: 9.0,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/max-welling-6b40b715',
    github_handle: null,
    bio: 'Pioneer of variational autoencoders (with Kingma) and group-equivariant CNNs. VP Research at Microsoft. Professor at University of Amsterdam. Key contributor to probabilistic deep learning and graph networks.',
    manually_reviewed: true,
    review_notes: 'VAE paper (with Kingma) is among the 10 most cited ML papers ever. Group-equivariant CNNs foundational for molecular and protein modeling. Amsterdam ML group is world-class.',
    geo: 'Amsterdam',
    degree: 'PhD',
    field: 'Deep Generative Models / Graph Learning',
  },
  {
    id: 'person-027',
    label: 'Person',
    name: 'Nando de Freitas',
    role: 'Research Scientist',
    company: 'Google DeepMind',
    composite_score: 8.7,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.7,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/nando-de-freitas',
    github_handle: null,
    bio: 'Expert in Bayesian optimization, probabilistic programming, and reinforcement learning. Research Scientist at DeepMind. Former Professor at Oxford and UBC. Contributed to modern BO and neural architecture search.',
    manually_reviewed: true,
    review_notes: 'Bayesian optimization expert. Influential in neural architecture search and sample-efficient RL. Strong teaching presence (popular YouTube lectures).',
    geo: 'London',
    degree: 'PhD',
    field: 'Bayesian Optimization / RL',
  },
  {
    id: 'person-028',
    label: 'Person',
    name: 'Diederik P. Kingma',
    role: 'Research Scientist',
    company: 'Google',
    composite_score: 9.2,
    founder_likelihood: 6.5,
    pedigree_score: 9.0,
    trajectory_score: 9.3,
    publication_score: 9.5,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/diederik-p-kingma',
    github_handle: 'dpkingma',
    bio: 'Inventor of the Variational Autoencoder (VAE) and Adam optimizer. VAE paper has ~50k citations; Adam optimizer is the default in virtually every deep learning system. Also co-created flow-based generative models (Glow).',
    manually_reviewed: true,
    review_notes: 'Adam optimizer is trained in every modern neural network. VAE is a cornerstone of generative AI. Two papers in the top 20 most-cited DL papers of all time.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Generative Models / Deep Learning',
  },
  {
    id: 'person-029',
    label: 'Person',
    name: 'Aaron Courville',
    role: 'Associate Professor',
    company: 'Université de Montréal / Mila',
    composite_score: 8.6,
    founder_likelihood: 5.5,
    pedigree_score: 8.5,
    trajectory_score: 8.7,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/aaron-courville',
    github_handle: null,
    bio: 'Co-author of the "Deep Learning" textbook with Bengio and Goodfellow. Core Mila researcher focusing on deep generative models, disentangled representations, and training dynamics of deep networks.',
    manually_reviewed: true,
    review_notes: '"Deep Learning" textbook co-author. Core Mila faculty. Less cited than Bengio/Goodfellow as solo researcher but highly influential through the textbook and Mila\'s output.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'Deep Generative Models',
  },
  {
    id: 'person-030',
    label: 'Person',
    name: 'Hugo Larochelle',
    role: 'Research Director',
    company: 'Google Brain / Mila',
    composite_score: 8.7,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.8,
    publication_score: 8.5,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/hugo-larochelle',
    github_handle: 'hlarochelle',
    bio: 'Research Director at Google Brain and core Mila researcher. Pioneer of meta-learning, few-shot learning, and deep learning training techniques. Led the NeurIPS community for several years as Program Chair.',
    manually_reviewed: true,
    review_notes: 'Led NeurIPS as Program Chair — shaped the field\'s research agenda. Meta-learning and few-shot learning contributor. Strong Montreal ecosystem anchor.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'Meta-Learning / Deep Learning',
  },
  {
    id: 'person-031',
    label: 'Person',
    name: 'Kyunghyun Cho',
    role: 'Professor',
    company: 'New York University / Prescient Design',
    composite_score: 8.8,
    founder_likelihood: 7.5,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 9.0,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/kyunghyun-cho',
    github_handle: 'kyunghyuncho',
    bio: 'Co-inventor of the GRU (Gated Recurrent Unit) and sequence-to-sequence learning with attention. NYU Professor and Research Scientist at Prescient Design (Genentech). Foundational contributions to neural machine translation.',
    manually_reviewed: true,
    review_notes: 'GRU and attention mechanism co-inventor. Seq2Seq with attention paper is a direct precursor to the Transformer. Highly cited (~100k). Crosses academia and drug discovery.',
    geo: 'New York',
    degree: 'PhD',
    field: 'NLP / Sequence Models',
  },
  {
    id: 'person-032',
    label: 'Person',
    name: 'Pedro Domingos',
    role: 'Professor',
    company: 'University of Washington',
    composite_score: 8.6,
    founder_likelihood: 5.5,
    pedigree_score: 9.0,
    trajectory_score: 8.4,
    publication_score: 9.0,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/pedro-domingos',
    github_handle: null,
    bio: 'Creator of Markov Logic Networks and the "Master Algorithm" framework for unified ML. Professor at UW Allen School. Wrote the popular science book "The Master Algorithm." IJCAI Computer Olympiad Champion.',
    manually_reviewed: true,
    review_notes: '"The Master Algorithm" reached mainstream audiences. Markov Logic Networks bridged probabilistic and logical reasoning. Critical perspective on deep learning is valuable counterpoint.',
    geo: 'Seattle',
    degree: 'PhD',
    field: 'Statistical Relational Learning / ML Theory',
  },
  {
    id: 'person-033',
    label: 'Person',
    name: 'Song Han',
    role: 'Associate Professor',
    company: 'MIT',
    composite_score: 8.9,
    founder_likelihood: 8.5,
    pedigree_score: 9.5,
    trajectory_score: 9.5,
    publication_score: 8.8,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/song-han-mit',
    github_handle: null,
    bio: 'Pioneer of efficient AI: model compression, neural network pruning, quantization, and TinyML. Co-founder of Ganymede and Neural Magic. Created the "Efficient Deep Learning" course at MIT. EfficientNet and deep compression inventor.',
    manually_reviewed: true,
    review_notes: 'Deep Compression paper is among most cited in hardware-aware DL. TinyML pioneer. Co-founded Neural Magic (raised $60M+). Rising star — MIT tenure track rapidly building reputation.',
    geo: 'Cambridge MA',
    degree: 'PhD',
    field: 'Efficient AI / Model Compression',
  },
  {
    id: 'person-034',
    label: 'Person',
    name: 'Daphne Koller',
    role: 'CEO & Co-Founder',
    company: 'insitro',
    composite_score: 9.2,
    founder_likelihood: 9.5,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 9.5,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/daphne-koller',
    github_handle: null,
    bio: 'Co-founder of Coursera (raised $500M+) and insitro (applying ML to drug discovery). Turing Award (2011). Pioneered probabilistic graphical models and Bayesian networks. Taught the most popular online ML course before Ng.',
    manually_reviewed: true,
    review_notes: 'Turing Award 2011. Co-founded Coursera. Now CEO of insitro ($400M raised) applying ML to drug discovery. One of the highest-impact founders from the AI academic world.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Probabilistic Graphical Models / ML for Biology',
  },
  {
    id: 'person-035',
    label: 'Person',
    name: 'Judea Pearl',
    role: 'Professor Emeritus',
    company: 'UCLA',
    composite_score: 9.5,
    founder_likelihood: 3.5,
    pedigree_score: 10.0,
    trajectory_score: 8.5,
    publication_score: 10.0,
    data_confidence: 9.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/judea-pearl',
    github_handle: null,
    bio: 'Turing Award (2011). Father of causal inference in AI. Invented Bayesian networks and the do-calculus for causal reasoning. His book "The Book of Why" brought causality to mainstream science.',
    manually_reviewed: true,
    review_notes: 'Turing Award 2011. Bayesian networks invented here. Do-calculus is the foundational math of causal AI. "The Book of Why" is landmark popular science. Emeritus but his framework is in every causal ML paper.',
    geo: 'Los Angeles',
    degree: 'PhD',
    field: 'Causal Inference / Bayesian Networks',
  },
  {
    id: 'person-036',
    label: 'Person',
    name: 'Tom Mitchell',
    role: 'University Professor',
    company: 'Carnegie Mellon University',
    composite_score: 8.8,
    founder_likelihood: 5.0,
    pedigree_score: 9.5,
    trajectory_score: 8.5,
    publication_score: 9.2,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/tom-mitchell-cmu',
    github_handle: null,
    bio: 'Author of "Machine Learning" (1997) — the definitive ML textbook for 20 years. Founder of Carnegie Mellon\'s Machine Learning Department. Created the "Never Ending Language Learner" (NELL) project.',
    manually_reviewed: true,
    review_notes: '"Machine Learning" textbook trained a generation of ML engineers. Founded CMU ML dept — first standalone ML department in the world. NELL is a pioneering continuous learning system.',
    geo: 'Pittsburgh',
    degree: 'PhD',
    field: 'Machine Learning / Cognitive Systems',
  },
  {
    id: 'person-037',
    label: 'Person',
    name: 'Andrej Karpathy',
    role: 'Independent Researcher & Founder',
    company: 'Eureka Labs (former Tesla / OpenAI)',
    composite_score: 9.3,
    founder_likelihood: 9.5,
    pedigree_score: 9.5,
    trajectory_score: 9.5,
    publication_score: 8.8,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/andrej-karpathy',
    github_handle: 'karpathy',
    bio: 'Founding member of OpenAI and former Sr. Director of AI at Tesla (Autopilot). Pioneer of large language models and self-supervised learning. Creator of neural network educational content followed by millions. Founded Eureka Labs.',
    manually_reviewed: true,
    review_notes: 'Tesla Autopilot AI lead. OpenAI founding member. "makemore" and nanoGPT GitHub repos have hundreds of thousands of stars. Founded Eureka Labs for AI education. Exceptional communicator and builder.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Computer Vision / LLMs / Self-Supervised Learning',
  },
  {
    id: 'person-038',
    label: 'Person',
    name: 'Wojciech Zaremba',
    role: 'Co-Founder',
    company: 'OpenAI',
    composite_score: 8.8,
    founder_likelihood: 9.8,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 8.2,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/wojciech-zaremba',
    github_handle: 'wojzaremba',
    bio: 'Co-Founder of OpenAI. Pioneer of neural network training methods, robotics learning, and recurrent architectures. Led OpenAI\'s work on code generation (Codex) and dexterous robotic manipulation.',
    manually_reviewed: true,
    review_notes: 'OpenAI co-founder. Led Codex (basis of GitHub Copilot). Robotics dexterous manipulation (Rubik\'s Cube with robot hand). One of the few founders combining robotics + LLMs at frontier level.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Deep Learning / Robotics',
  },
  {
    id: 'person-039',
    label: 'Person',
    name: 'Oriol Vinyals',
    role: 'VP Research',
    company: 'Google DeepMind',
    composite_score: 9.0,
    founder_likelihood: 5.0,
    pedigree_score: 9.5,
    trajectory_score: 9.2,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/oriol-vinyals',
    github_handle: null,
    bio: 'Pioneer of sequence-to-sequence learning, attention mechanisms, and AlphaStar (AI that defeated pro StarCraft players). VP Research at DeepMind. Co-invented Pointer Networks and the neural Turing machine concept.',
    manually_reviewed: true,
    review_notes: 'AlphaStar defeated top human pros at StarCraft — far more complex than Go. Seq2Seq and attention co-inventor. Pointer Networks and Set2Set widely used.',
    geo: 'London',
    degree: 'PhD',
    field: 'Sequence Learning / Deep RL',
  },
  {
    id: 'person-040',
    label: 'Person',
    name: 'Timnit Gebru',
    role: 'Founder & Executive Director',
    company: 'DAIR Institute',
    composite_score: 8.5,
    founder_likelihood: 8.5,
    pedigree_score: 9.5,
    trajectory_score: 8.8,
    publication_score: 7.8,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/timnit-gebru',
    github_handle: 'timnitgebru',
    bio: 'Founder of the DAIR Institute and former co-lead of Google\'s Ethical AI team. Pioneer of algorithmic fairness, model cards, and dataset documentation. "Stochastic Parrots" paper triggered major AI safety discourse.',
    manually_reviewed: true,
    review_notes: 'Founded DAIR Institute after high-profile departure from Google. "Stochastic Parrots" is landmark AI ethics paper. Model cards framework adopted industry-wide. Important policy voice.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'AI Ethics / Algorithmic Fairness',
  },
  {
    id: 'person-041',
    label: 'Person',
    name: 'Trevor Darrell',
    role: 'Professor',
    company: 'UC Berkeley',
    composite_score: 8.7,
    founder_likelihood: 6.5,
    pedigree_score: 9.5,
    trajectory_score: 8.7,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/trevor-darrell',
    github_handle: null,
    bio: 'Pioneer of transfer learning and domain adaptation in computer vision. Led BAIR (Berkeley AI Research). Co-creator of the Caffe deep learning framework. Professor at UC Berkeley directing the VSSL lab.',
    manually_reviewed: true,
    review_notes: 'Caffe framework co-creator (before TensorFlow/PyTorch). Transfer learning and domain adaptation pioneer. BAIR lab director. H-index ~100+. Trains many top CV researchers.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Computer Vision / Transfer Learning',
  },
  {
    id: 'person-042',
    label: 'Person',
    name: 'Lise Getoor',
    role: 'Professor',
    company: 'UC Santa Cruz',
    composite_score: 8.3,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.3,
    publication_score: 8.5,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/lise-getoor',
    github_handle: null,
    bio: 'Pioneer of statistical relational learning and probabilistic graphical models for structured data. Professor at UC Santa Cruz. Co-editor of "Introduction to Statistical Relational Learning." Elected ACM Fellow.',
    manually_reviewed: true,
    review_notes: 'SRL and PSL (Probabilistic Soft Logic) pioneer. Foundational work for graph-based ML and knowledge graph reasoning. ACM Fellow. Important for neuro-symbolic AI directions.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'Statistical Relational Learning',
  },
  {
    id: 'person-043',
    label: 'Person',
    name: 'Samy Bengio',
    role: 'Research Director',
    company: 'Apple',
    composite_score: 8.5,
    founder_likelihood: 4.5,
    pedigree_score: 8.5,
    trajectory_score: 8.5,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/samy-bengio',
    github_handle: null,
    bio: 'Research Director at Apple AI Research. Younger brother of Yoshua Bengio. Pioneer of structured prediction in NLP, adversarial training, and neural network optimization. Former Google Brain Research Scientist.',
    manually_reviewed: true,
    review_notes: 'Less prominent than Yoshua but still highly influential (H-index ~80). Adversarial training and curriculum learning contributions are widely used. Left Google Brain for Apple.',
    geo: 'Bay Area',
    degree: 'PhD',
    field: 'NLP / Adversarial Training',
  },
  {
    id: 'person-044',
    label: 'Person',
    name: 'Alex Graves',
    role: 'Research Scientist',
    company: 'Google DeepMind',
    composite_score: 9.1,
    founder_likelihood: 4.5,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 9.3,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/alex-graves',
    github_handle: null,
    bio: 'Inventor of the Connectionist Temporal Classification (CTC) algorithm powering modern speech recognition. Creator of Neural Turing Machines and differentiable memory architectures. Senior scientist at DeepMind.',
    manually_reviewed: true,
    review_notes: 'CTC algorithm is in every speech recognition system (Siri, Google, Alexa). Neural Turing Machine opened the memory-augmented network research area. Extremely high citation/paper ratio.',
    geo: 'London',
    degree: 'PhD',
    field: 'Sequence Models / Memory Networks',
  },
  {
    id: 'person-045',
    label: 'Person',
    name: 'Raia Hadsell',
    role: 'VP Research',
    company: 'Google DeepMind',
    composite_score: 8.6,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.8,
    publication_score: 8.2,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/raia-hadsell',
    github_handle: null,
    bio: 'VP Research at DeepMind leading robotics and continual learning research. Pioneer of metric learning and contrastive loss (basis of SimCLR and modern self-supervised learning). Robotics navigation expert.',
    manually_reviewed: true,
    review_notes: 'Contrastive loss paper is a precursor to all modern self-supervised learning. VP Research at DeepMind. Leading robotics agent and continual learning programs at scale.',
    geo: 'London',
    degree: 'PhD',
    field: 'Robotics / Continual Learning',
  },
  {
    id: 'person-046',
    label: 'Person',
    name: 'Nir Friedman',
    role: 'Professor',
    company: 'Hebrew University of Jerusalem',
    composite_score: 8.5,
    founder_likelihood: 5.5,
    pedigree_score: 9.0,
    trajectory_score: 8.3,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/nir-friedman',
    github_handle: null,
    bio: 'Pioneer of probabilistic graphical models and computational biology. Co-author of "Probabilistic Graphical Models" with Koller. Professor at Hebrew University. Applied PGMs to gene expression and network inference.',
    manually_reviewed: true,
    review_notes: 'PGM textbook with Koller is the gold standard reference. Gene network inference work has deep bio impact. Israeli AI ecosystem anchor.',
    geo: 'Jerusalem',
    degree: 'PhD',
    field: 'Probabilistic Graphical Models / Computational Biology',
  },
  {
    id: 'person-047',
    label: 'Person',
    name: 'Koray Kavukcuoglu',
    role: 'VP Research',
    company: 'Google DeepMind',
    composite_score: 9.0,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 9.2,
    publication_score: 8.8,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/koray-kavukcuoglu',
    github_handle: null,
    bio: 'VP Research at DeepMind. Co-inventor of DQN (Deep Q-Network) that kicked off deep RL research. Co-authored the landmark Atari paper. Leading deep learning and RL research programs at DeepMind.',
    manually_reviewed: true,
    review_notes: 'DQN paper is one of the most impactful in RL history — playing Atari from pixels. VP Research at DeepMind overseeing major research programs. Critical DeepMind institutional knowledge.',
    geo: 'London',
    degree: 'PhD',
    field: 'Deep Reinforcement Learning',
  },
  {
    id: 'person-048',
    label: 'Person',
    name: 'Volodymyr Mnih',
    role: 'Research Scientist',
    company: 'Google DeepMind',
    composite_score: 8.9,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 8.9,
    publication_score: 9.0,
    data_confidence: 8.5,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/volodymyr-mnih',
    github_handle: 'vmnih',
    bio: 'Lead author of the DQN (Deep Q-Network) and Asynchronous Advantage Actor-Critic (A3C) papers. Both are landmark papers that shaped modern deep reinforcement learning. Research Scientist at DeepMind.',
    manually_reviewed: true,
    review_notes: 'DQN and A3C first-author. These papers collectively have 25k+ citations. DQN playing Atari from pixels was a landmark moment. A3C enabled practical deep RL at scale.',
    geo: 'London',
    degree: 'PhD',
    field: 'Deep Reinforcement Learning',
  },
  {
    id: 'person-049',
    label: 'Person',
    name: 'Blaise Agüera y Arcas',
    role: 'VP & Fellow',
    company: 'Google',
    composite_score: 8.4,
    founder_likelihood: 6.0,
    pedigree_score: 8.5,
    trajectory_score: 8.5,
    publication_score: 7.8,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/blaise-aguera-y-arcas',
    github_handle: null,
    bio: 'VP and Fellow at Google. Pioneer of federated learning (privacy-preserving distributed ML) and creative AI applications. Led development of artistic neural style transfer and the Magenta project. TED speaker on AI consciousness.',
    manually_reviewed: true,
    review_notes: 'Federated learning pioneer — critical for privacy-preserving ML in healthcare. Magenta project bridges AI and art. Unique cross-disciplinary profile. TED talks well-received.',
    geo: 'Seattle',
    degree: null,
    field: 'Federated Learning / Generative AI',
  },

  // ── INSTITUTION NODES ─────────────────────────────────────────────────────

  {
    id: 'inst-001',
    label: 'Institution',
    name: 'MIT',
    type: 'university',
    country: 'USA',
    world_rank: 1,
  },
  {
    id: 'inst-002',
    label: 'Institution',
    name: 'Stanford University',
    type: 'university',
    country: 'USA',
    world_rank: 2,
  },
  {
    id: 'inst-003',
    label: 'Institution',
    name: 'UC Berkeley',
    type: 'university',
    country: 'USA',
    world_rank: 3,
  },
  {
    id: 'inst-004',
    label: 'Institution',
    name: 'Carnegie Mellon University',
    type: 'university',
    country: 'USA',
    world_rank: 4,
  },
  {
    id: 'inst-005',
    label: 'Institution',
    name: 'University of Toronto',
    type: 'university',
    country: 'Canada',
    world_rank: 6,
  },
  {
    id: 'inst-006',
    label: 'Institution',
    name: 'Université de Montréal / Mila',
    type: 'university',
    country: 'Canada',
    world_rank: 7,
  },
  {
    id: 'inst-007',
    label: 'Institution',
    name: 'University of Cambridge',
    type: 'university',
    country: 'UK',
    world_rank: 5,
  },
  {
    id: 'inst-008',
    label: 'Institution',
    name: 'University of Oxford',
    type: 'university',
    country: 'UK',
    world_rank: 8,
  },
  {
    id: 'inst-009',
    label: 'Institution',
    name: 'University College London',
    type: 'university',
    country: 'UK',
    world_rank: 9,
  },
  {
    id: 'inst-010',
    label: 'Institution',
    name: 'University of Edinburgh',
    type: 'university',
    country: 'UK',
    world_rank: 15,
  },
  {
    id: 'inst-011',
    label: 'Institution',
    name: 'TU Munich',
    type: 'university',
    country: 'Germany',
    world_rank: 12,
  },
  {
    id: 'inst-012',
    label: 'Institution',
    name: 'MPI for Intelligent Systems',
    type: 'research_institute',
    country: 'Germany',
    world_rank: 10,
  },
  {
    id: 'inst-013',
    label: 'Institution',
    name: 'New York University',
    type: 'university',
    country: 'USA',
    world_rank: 11,
  },
  {
    id: 'inst-014',
    label: 'Institution',
    name: 'University of Washington',
    type: 'university',
    country: 'USA',
    world_rank: 13,
  },
  {
    id: 'inst-015',
    label: 'Institution',
    name: 'University of Alberta',
    type: 'university',
    country: 'Canada',
    world_rank: 20,
  },
  {
    id: 'inst-016',
    label: 'Institution',
    name: 'University of Amsterdam',
    type: 'university',
    country: 'Netherlands',
    world_rank: 18,
  },
  {
    id: 'inst-017',
    label: 'Institution',
    name: 'UCLA',
    type: 'university',
    country: 'USA',
    world_rank: 14,
  },
  {
    id: 'inst-018',
    label: 'Institution',
    name: 'UC San Diego',
    type: 'university',
    country: 'USA',
    world_rank: 16,
  },
  {
    id: 'inst-019',
    label: 'Institution',
    name: 'Google DeepMind',
    type: 'company',
    country: 'UK',
    world_rank: 1,
  },
  {
    id: 'inst-020',
    label: 'Institution',
    name: 'Caltech',
    type: 'university',
    country: 'USA',
    world_rank: 5,
  },
  {
    id: 'inst-021',
    label: 'Institution',
    name: 'Hebrew University of Jerusalem',
    type: 'university',
    country: 'Israel',
    world_rank: 25,
  },

  // ── GEOGRAPHIC CLUSTER NODES ───────────────────────────────────────────────

  {
    id: 'geo-001',
    label: 'GeographicCluster',
    name: 'Bay Area',
    country: 'USA',
  },
  {
    id: 'geo-002',
    label: 'GeographicCluster',
    name: 'London',
    country: 'UK',
  },
  {
    id: 'geo-003',
    label: 'GeographicCluster',
    name: 'Montreal',
    country: 'Canada',
  },
  {
    id: 'geo-004',
    label: 'GeographicCluster',
    name: 'New York',
    country: 'USA',
  },
  {
    id: 'geo-005',
    label: 'GeographicCluster',
    name: 'Toronto',
    country: 'Canada',
  },
  {
    id: 'geo-006',
    label: 'GeographicCluster',
    name: 'Cambridge UK',
    country: 'UK',
  },
  {
    id: 'geo-007',
    label: 'GeographicCluster',
    name: 'Pittsburgh',
    country: 'USA',
  },
  {
    id: 'geo-008',
    label: 'GeographicCluster',
    name: 'Seattle',
    country: 'USA',
  },
  {
    id: 'geo-009',
    label: 'GeographicCluster',
    name: 'Tübingen',
    country: 'Germany',
  },
  {
    id: 'geo-010',
    label: 'GeographicCluster',
    name: 'Oxford',
    country: 'UK',
  },
  {
    id: 'geo-011',
    label: 'GeographicCluster',
    name: 'Edmonton',
    country: 'Canada',
  },
  {
    id: 'geo-012',
    label: 'GeographicCluster',
    name: 'Amsterdam',
    country: 'Netherlands',
  },
  {
    id: 'geo-013',
    label: 'GeographicCluster',
    name: 'Cambridge MA',
    country: 'USA',
  },
  {
    id: 'geo-014',
    label: 'GeographicCluster',
    name: 'Los Angeles',
    country: 'USA',
  },
  {
    id: 'geo-015',
    label: 'GeographicCluster',
    name: 'Lugano',
    country: 'Switzerland',
  },
  {
    id: 'geo-016',
    label: 'GeographicCluster',
    name: 'Jerusalem',
    country: 'Israel',
  },
]

export const mockEdges = [
  // ── ALUMNI_OF (PhD institution) ───────────────────────────────────────────
  { id: 'e001', source: 'person-001', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — Pierre and Marie Curie' },
  { id: 'e002', source: 'person-002', target: 'inst-010',  type: 'ALUMNI_OF',        label: 'PhD — Edinburgh' },
  { id: 'e003', source: 'person-003', target: 'inst-005',  type: 'ALUMNI_OF',        label: 'PhD — McGill (at Mila)' },
  { id: 'e004', source: 'person-004', target: 'inst-003',  type: 'ALUMNI_OF',        label: 'PhD — UC Berkeley' },
  { id: 'e005', source: 'person-005', target: 'inst-020',  type: 'ALUMNI_OF',        label: 'PhD — Caltech' },
  { id: 'e006', source: 'person-006', target: 'inst-011',  type: 'ALUMNI_OF',        label: 'PhD — TU Munich' },
  { id: 'e007', source: 'person-007', target: 'inst-011',  type: 'ALUMNI_OF',        label: 'PhD — TU Berlin' },
  { id: 'e008', source: 'person-008', target: 'inst-018',  type: 'ALUMNI_OF',        label: 'PhD — UC San Diego' },
  { id: 'e009', source: 'person-009', target: 'inst-009',  type: 'ALUMNI_OF',        label: 'PhD — UCL' },
  { id: 'e010', source: 'person-010', target: 'inst-014',  type: 'ALUMNI_OF',        label: 'PhD — U Washington' },
  { id: 'e011', source: 'person-011', target: 'inst-006',  type: 'ALUMNI_OF',        label: 'PhD — Montréal' },
  { id: 'e012', source: 'person-012', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e013', source: 'person-013', target: 'inst-005',  type: 'ALUMNI_OF',        label: 'PhD — U Toronto' },
  { id: 'e014', source: 'person-014', target: 'inst-005',  type: 'ALUMNI_OF',        label: 'PhD — U Toronto' },
  { id: 'e015', source: 'person-015', target: 'inst-001',  type: 'ALUMNI_OF',        label: 'PhD — MIT' },
  { id: 'e016', source: 'person-016', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e017', source: 'person-017', target: 'inst-001',  type: 'ALUMNI_OF',        label: 'PhD — MIT' },
  { id: 'e018', source: 'person-018', target: 'inst-009',  type: 'ALUMNI_OF',        label: 'PhD — UCL' },
  { id: 'e019', source: 'person-019', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e020', source: 'person-020', target: 'inst-003',  type: 'ALUMNI_OF',        label: 'PhD — UC Berkeley' },
  { id: 'e021', source: 'person-021', target: 'inst-010',  type: 'ALUMNI_OF',        label: 'PhD — Edinburgh' },
  { id: 'e022', source: 'person-022', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e023', source: 'person-023', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e024', source: 'person-024', target: 'inst-014',  type: 'ALUMNI_OF',        label: 'PhD — UMass Amherst' },
  { id: 'e025', source: 'person-025', target: 'inst-021',  type: 'ALUMNI_OF',        label: 'PhD — Technion' },
  { id: 'e026', source: 'person-026', target: 'inst-020',  type: 'ALUMNI_OF',        label: 'PhD — Caltech' },
  { id: 'e027', source: 'person-027', target: 'inst-007',  type: 'ALUMNI_OF',        label: 'PhD — Cambridge' },
  { id: 'e028', source: 'person-028', target: 'inst-016',  type: 'ALUMNI_OF',        label: 'PhD — Amsterdam' },
  { id: 'e029', source: 'person-029', target: 'inst-015',  type: 'ALUMNI_OF',        label: 'PhD — U Alberta' },
  { id: 'e030', source: 'person-030', target: 'inst-006',  type: 'ALUMNI_OF',        label: 'PhD — Montréal' },
  { id: 'e031', source: 'person-031', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — NYU (Aalto exchange)' },
  { id: 'e032', source: 'person-032', target: 'inst-018',  type: 'ALUMNI_OF',        label: 'PhD — UC Irvine' },
  { id: 'e033', source: 'person-033', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e034', source: 'person-034', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e035', source: 'person-035', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — Polytechnic Brooklyn' },
  { id: 'e036', source: 'person-036', target: 'inst-004',  type: 'ALUMNI_OF',        label: 'PhD — Cornell / CMU' },
  { id: 'e037', source: 'person-037', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e038', source: 'person-038', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — NYU' },
  { id: 'e039', source: 'person-039', target: 'inst-018',  type: 'ALUMNI_OF',        label: 'PhD — UC San Diego' },
  { id: 'e040', source: 'person-040', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e041', source: 'person-041', target: 'inst-001',  type: 'ALUMNI_OF',        label: 'PhD — MIT' },
  { id: 'e042', source: 'person-042', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e043', source: 'person-043', target: 'inst-006',  type: 'ALUMNI_OF',        label: 'PhD — Montréal' },
  { id: 'e044', source: 'person-044', target: 'inst-009',  type: 'ALUMNI_OF',        label: 'PhD — UCL' },
  { id: 'e045', source: 'person-045', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — NYU' },
  { id: 'e046', source: 'person-046', target: 'inst-002',  type: 'ALUMNI_OF',        label: 'PhD — Stanford' },
  { id: 'e047', source: 'person-047', target: 'inst-013',  type: 'ALUMNI_OF',        label: 'PhD — NYU' },
  { id: 'e048', source: 'person-048', target: 'inst-005',  type: 'ALUMNI_OF',        label: 'PhD — U Toronto' },

  // ── LOCATED_IN ────────────────────────────────────────────────────────────
  { id: 'e101', source: 'person-001', target: 'geo-004',   type: 'LOCATED_IN',       label: 'New York' },
  { id: 'e102', source: 'person-002', target: 'geo-005',   type: 'LOCATED_IN',       label: 'Toronto' },
  { id: 'e103', source: 'person-003', target: 'geo-003',   type: 'LOCATED_IN',       label: 'Montreal' },
  { id: 'e104', source: 'person-004', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e105', source: 'person-005', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e106', source: 'person-006', target: 'geo-015',   type: 'LOCATED_IN',       label: 'Lugano' },
  { id: 'e107', source: 'person-007', target: 'geo-009',   type: 'LOCATED_IN',       label: 'Tübingen' },
  { id: 'e108', source: 'person-008', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e109', source: 'person-009', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e110', source: 'person-010', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e111', source: 'person-011', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e112', source: 'person-012', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e113', source: 'person-013', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e114', source: 'person-014', target: 'geo-007',   type: 'LOCATED_IN',       label: 'Pittsburgh' },
  { id: 'e115', source: 'person-015', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e116', source: 'person-016', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e117', source: 'person-017', target: 'geo-006',   type: 'LOCATED_IN',       label: 'Cambridge UK' },
  { id: 'e118', source: 'person-018', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e119', source: 'person-019', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e120', source: 'person-020', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e121', source: 'person-021', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e122', source: 'person-022', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e123', source: 'person-023', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e124', source: 'person-024', target: 'geo-011',   type: 'LOCATED_IN',       label: 'Edmonton' },
  { id: 'e125', source: 'person-025', target: 'geo-010',   type: 'LOCATED_IN',       label: 'Oxford' },
  { id: 'e126', source: 'person-026', target: 'geo-012',   type: 'LOCATED_IN',       label: 'Amsterdam' },
  { id: 'e127', source: 'person-027', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e128', source: 'person-028', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e129', source: 'person-029', target: 'geo-003',   type: 'LOCATED_IN',       label: 'Montreal' },
  { id: 'e130', source: 'person-030', target: 'geo-003',   type: 'LOCATED_IN',       label: 'Montreal' },
  { id: 'e131', source: 'person-031', target: 'geo-004',   type: 'LOCATED_IN',       label: 'New York' },
  { id: 'e132', source: 'person-032', target: 'geo-008',   type: 'LOCATED_IN',       label: 'Seattle' },
  { id: 'e133', source: 'person-033', target: 'geo-013',   type: 'LOCATED_IN',       label: 'Cambridge MA' },
  { id: 'e134', source: 'person-034', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e135', source: 'person-035', target: 'geo-014',   type: 'LOCATED_IN',       label: 'Los Angeles' },
  { id: 'e136', source: 'person-036', target: 'geo-007',   type: 'LOCATED_IN',       label: 'Pittsburgh' },
  { id: 'e137', source: 'person-037', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e138', source: 'person-038', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e139', source: 'person-039', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e140', source: 'person-040', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e141', source: 'person-041', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e142', source: 'person-042', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e143', source: 'person-043', target: 'geo-001',   type: 'LOCATED_IN',       label: 'Bay Area' },
  { id: 'e144', source: 'person-044', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e145', source: 'person-045', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e146', source: 'person-046', target: 'geo-016',   type: 'LOCATED_IN',       label: 'Jerusalem' },
  { id: 'e147', source: 'person-047', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e148', source: 'person-048', target: 'geo-002',   type: 'LOCATED_IN',       label: 'London' },
  { id: 'e149', source: 'person-049', target: 'geo-008',   type: 'LOCATED_IN',       label: 'Seattle' },

  // ── ADVISED_BY / MENTORSHIP ───────────────────────────────────────────────
  { id: 'e201', source: 'person-013', target: 'person-002', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e202', source: 'person-014', target: 'person-002', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e203', source: 'person-011', target: 'person-003', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e204', source: 'person-029', target: 'person-003', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e205', source: 'person-030', target: 'person-003', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e206', source: 'person-019', target: 'person-004', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e207', source: 'person-020', target: 'person-019', type: 'ADVISED_BY',      label: 'PhD co-advisor' },
  { id: 'e208', source: 'person-012', target: 'person-004', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e209', source: 'person-037', target: 'person-005', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e210', source: 'person-044', target: 'person-006', type: 'ADVISED_BY',      label: 'PhD advisor' },
  { id: 'e211', source: 'person-028', target: 'person-026', type: 'ADVISED_BY',      label: 'PhD advisor' },

  // ── CO_AUTHORED_WITH (key collaborations) ─────────────────────────────────
  { id: 'e301', source: 'person-002', target: 'person-003', type: 'CO_AUTHORED_WITH', label: 'Deep Learning (NeurIPS 2006)' },
  { id: 'e302', source: 'person-003', target: 'person-011', type: 'CO_AUTHORED_WITH', label: 'GAN (NeurIPS 2014)' },
  { id: 'e303', source: 'person-003', target: 'person-029', type: 'CO_AUTHORED_WITH', label: 'Deep Learning textbook 2016' },
  { id: 'e304', source: 'person-003', target: 'person-011', type: 'CO_AUTHORED_WITH', label: 'Deep Learning textbook 2016' },
  { id: 'e305', source: 'person-009', target: 'person-018', type: 'CO_AUTHORED_WITH', label: 'AlphaGo (Nature 2016)' },
  { id: 'e306', source: 'person-009', target: 'person-047', type: 'CO_AUTHORED_WITH', label: 'DQN (Nature 2015)' },
  { id: 'e307', source: 'person-047', target: 'person-048', type: 'CO_AUTHORED_WITH', label: 'DQN first paper 2013' },
  { id: 'e308', source: 'person-013', target: 'person-001', type: 'CO_AUTHORED_WITH', label: 'AlexNet (NeurIPS 2012)' },
  { id: 'e309', source: 'person-013', target: 'person-002', type: 'CO_AUTHORED_WITH', label: 'AlexNet (NeurIPS 2012)' },
  { id: 'e310', source: 'person-026', target: 'person-028', type: 'CO_AUTHORED_WITH', label: 'VAE (ICLR 2014)' },
  { id: 'e311', source: 'person-019', target: 'person-012', type: 'CO_AUTHORED_WITH', label: 'TRPO (ICML 2015)' },
  { id: 'e312', source: 'person-020', target: 'person-019', type: 'CO_AUTHORED_WITH', label: 'MAML (ICML 2017)' },
  { id: 'e313', source: 'person-031', target: 'person-039', type: 'CO_AUTHORED_WITH', label: 'Attention mechanism (2015)' },
  { id: 'e314', source: 'person-034', target: 'person-046', type: 'CO_AUTHORED_WITH', label: 'PGM textbook 2009' },
  { id: 'e315', source: 'person-005', target: 'person-022', type: 'CO_AUTHORED_WITH', label: 'Computer Vision (ICCV papers)' },
  { id: 'e316', source: 'person-023', target: 'person-008', type: 'CO_AUTHORED_WITH', label: 'AI safety research' },

  // ── EMPLOYED_AT ───────────────────────────────────────────────────────────
  { id: 'e401', source: 'person-009', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'CEO' },
  { id: 'e402', source: 'person-018', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'Research Scientist' },
  { id: 'e403', source: 'person-021', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'Research Director' },
  { id: 'e404', source: 'person-027', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'Research Scientist' },
  { id: 'e405', source: 'person-039', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'VP Research' },
  { id: 'e406', source: 'person-044', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'Research Scientist' },
  { id: 'e407', source: 'person-045', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'VP Research' },
  { id: 'e408', source: 'person-047', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'VP Research' },
  { id: 'e409', source: 'person-048', target: 'inst-019',  type: 'EMPLOYED_AT',      label: 'Research Scientist' },
  { id: 'e410', source: 'person-002', target: 'inst-005',  type: 'EMPLOYED_AT',      label: 'Emeritus Professor' },
  { id: 'e411', source: 'person-003', target: 'inst-006',  type: 'EMPLOYED_AT',      label: 'Scientific Director' },
  { id: 'e412', source: 'person-008', target: 'inst-003',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e413', source: 'person-023', target: 'inst-003',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e414', source: 'person-022', target: 'inst-003',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e415', source: 'person-005', target: 'inst-002',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e416', source: 'person-016', target: 'inst-002',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e417', source: 'person-015', target: 'inst-002',  type: 'EMPLOYED_AT',      label: 'Associate Professor' },
  { id: 'e418', source: 'person-020', target: 'inst-002',  type: 'EMPLOYED_AT',      label: 'Assistant Professor' },
  { id: 'e419', source: 'person-024', target: 'inst-015',  type: 'EMPLOYED_AT',      label: 'Research Scientist' },
  { id: 'e420', source: 'person-036', target: 'inst-004',  type: 'EMPLOYED_AT',      label: 'University Professor' },
  { id: 'e421', source: 'person-014', target: 'inst-004',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e422', source: 'person-007', target: 'inst-012',  type: 'EMPLOYED_AT',      label: 'Director' },
  { id: 'e423', source: 'person-033', target: 'inst-001',  type: 'EMPLOYED_AT',      label: 'Associate Professor' },
  { id: 'e424', source: 'person-001', target: 'inst-013',  type: 'EMPLOYED_AT',      label: 'Silver Professor' },
  { id: 'e425', source: 'person-031', target: 'inst-013',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e426', source: 'person-017', target: 'inst-007',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e427', source: 'person-025', target: 'inst-008',  type: 'EMPLOYED_AT',      label: 'DeepMind Professor' },
  { id: 'e428', source: 'person-026', target: 'inst-016',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e429', source: 'person-046', target: 'inst-021',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e430', source: 'person-032', target: 'inst-014',  type: 'EMPLOYED_AT',      label: 'Professor' },
  { id: 'e431', source: 'person-035', target: 'inst-017',  type: 'EMPLOYED_AT',      label: 'Professor Emeritus' },
]
