/**
 * Mock graph data — AI Safety Researcher rankings (top 40 globally).
 * Shape matches what neo4j.js returns so components are driver-agnostic.
 * Source: AI_Safety_Researchers_Rankings.pdf / research compiled April 2026.
 */

const mockSafetyPersonNodes = [
  // ── PERSON NODES ──────────────────────────────────────────────────────────

  {
    id: 'safety-001',
    label: 'Person',
    name: 'Stuart Russell',
    role: 'Professor & CHAI Director',
    company: 'UC Berkeley / CHAI',
    composite_score: 9.3,
    founder_likelihood: 9.0,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 10.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/stuart-russell-ai',
    github_handle: null,
    bio: 'Co-authored the definitive AIMA textbook, used in 1,500+ universities worldwide. Founded the Center for Human-Compatible AI (CHAI) at Berkeley. Author of Human Compatible (2019). Advises UK Ministry of Defence and UN on AI safety. The most credentialed AI safety academic globally.',
    manually_reviewed: true,
    review_notes: 'Field-defining contributions across theory and policy. AIMA + Human Compatible are both seminal works. H-index ~105, ~150k citations.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'AI Alignment / Safety Governance',
  },
  {
    id: 'safety-002',
    label: 'Person',
    name: 'Yoshua Bengio',
    role: 'Scientific Director & Founder',
    company: 'Mila / LawZero',
    composite_score: 9.2,
    founder_likelihood: 9.0,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 10.0,
    data_confidence: 10.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/yoshua-bengio',
    github_handle: 'yoshuabengio',
    bio: 'Turing Award laureate (2018) and first scientist to reach 1M+ citations (November 2025). Chaired the International AI Safety Report. Founded LawZero, a safety-focused AI lab. Signed the AI pause open letter and has become one of the loudest voices for existential AI risk mitigation.',
    manually_reviewed: true,
    review_notes: 'Most-cited living computer scientist. Pivoted primary focus to AI safety in 2023. H-index ~180, 1M+ citations.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'AI Safety / Safe-by-Design AI',
  },
  {
    id: 'safety-003',
    label: 'Person',
    name: 'Ilya Sutskever',
    role: 'Co-Founder & Chief Scientist',
    company: 'Safe Superintelligence (SSI)',
    composite_score: 9.1,
    founder_likelihood: 10.0,
    pedigree_score: 10.0,
    trajectory_score: 10.0,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/ilya-sutskever',
    github_handle: null,
    bio: 'Co-founded OpenAI and co-invented RLHF. Co-invented AlexNet with Hinton. Left OpenAI to found SSI, now valued at $32B, with the singular mission of safe superintelligence. Received the NeurIPS Test of Time Award three consecutive times. ~774k citations.',
    manually_reviewed: true,
    review_notes: 'One of the highest-cited computer scientists. SSI is the highest-stakes safety-only lab in existence. H-index ~102.',
    geo: 'Palo Alto',
    degree: 'PhD',
    field: 'Superintelligence Safety / RLHF',
  },
  {
    id: 'safety-004',
    label: 'Person',
    name: 'Dario Amodei',
    role: 'CEO & Co-Founder',
    company: 'Anthropic',
    composite_score: 9.0,
    founder_likelihood: 10.0,
    pedigree_score: 9.0,
    trajectory_score: 10.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/dario-amodei',
    github_handle: null,
    bio: 'Co-invented RLHF at OpenAI. Co-founded Anthropic, the world\'s most prominent safety-focused frontier AI lab. Authored the Responsible Scaling Policy and developed Constitutional AI. Anthropic raised $7.3B in 2024 and is widely considered the safety-first alternative to OpenAI.',
    manually_reviewed: true,
    review_notes: 'Leads the world\'s most prominent safety-focused frontier AI lab. H-index ~60, ~100k citations.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'Constitutional AI / Alignment',
  },
  {
    id: 'safety-005',
    label: 'Person',
    name: 'John Schulman',
    role: 'Co-Founder',
    company: 'Thinking Machines Lab',
    composite_score: 8.9,
    founder_likelihood: 9.0,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/john-schulman',
    github_handle: 'joschu',
    bio: 'Invented Proximal Policy Optimization (PPO), with 36,000+ citations, the backbone of RLHF training across all major AI labs. Architect of ChatGPT. Co-authored InstructGPT. Left OpenAI for Anthropic and then founded Thinking Machines Lab. ~177k total citations.',
    manually_reviewed: true,
    review_notes: 'PPO is the bedrock of modern RLHF. H-index ~64. Serially impactful.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'RLHF / RL Theory / LLM Safety',
  },
  {
    id: 'safety-006',
    label: 'Person',
    name: 'Paul Christiano',
    role: 'Founder',
    company: 'ARC / NIST',
    composite_score: 8.8,
    founder_likelihood: 9.0,
    pedigree_score: 10.0,
    trajectory_score: 9.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: null,
    github_handle: 'paulfchristiano',
    bio: 'Co-invented RLHF in 2017, shaping the entire field of alignment. Formulated Eliciting Latent Knowledge (ELK). Founded the Alignment Research Center (ARC). Shaped both UK AISI and the White House AI Executive Order. The intellectual center of empirical alignment research.',
    manually_reviewed: true,
    review_notes: 'ELK is a blueprint for safety agenda. Co-invented RLHF. H-index ~21, ~46k citations.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'AI Alignment / Scalable Oversight / ELK',
  },
  {
    id: 'safety-007',
    label: 'Person',
    name: 'Jan Leike',
    role: 'VP of Alignment',
    company: 'Anthropic',
    composite_score: 8.7,
    founder_likelihood: 8.0,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/jan-leike',
    github_handle: null,
    bio: 'Co-led OpenAI\'s Superalignment team until his high-profile resignation in 2024, citing safety concerns. His departure was a landmark AI safety moment. Named to TIME 100 AI list in 2023 and 2024. Now heads alignment research at Anthropic.',
    manually_reviewed: true,
    review_notes: 'His public OpenAI resignation shaped public discourse on lab safety culture. H-index ~32, ~25k citations.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'Superalignment / Scalable Oversight / RLHF',
  },
  {
    id: 'safety-008',
    label: 'Person',
    name: 'Chris Olah',
    role: 'Interpretability Research Lead',
    company: 'Anthropic',
    composite_score: 8.6,
    founder_likelihood: 9.0,
    pedigree_score: 8.0,
    trajectory_score: 10.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: null,
    github_handle: 'colah',
    bio: 'Pioneered the field of mechanistic interpretability, aimed at understanding what neural networks actually compute. His team at Anthropic extracted 34M+ features from Claude 3 Sonnet. Named to TIME 100 AI. Exceptional trajectory — no PhD, yet one of the most influential safety researchers alive.',
    manually_reviewed: true,
    review_notes: 'Founder of mechanistic interpretability. ~111k citations, H-index ~52. No PhD — extraordinary.',
    geo: 'San Francisco',
    degree: 'No PhD',
    field: 'Mechanistic Interpretability / Neural Circuits',
  },
  {
    id: 'safety-009',
    label: 'Person',
    name: 'Geoffrey Irving',
    role: 'Technical Director',
    company: 'UK AI Security Institute',
    composite_score: 8.5,
    founder_likelihood: 7.0,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/geoffrey-irving',
    github_handle: null,
    bio: 'Co-authored the seminal "AI Safety via Debate" paper and co-authored TensorFlow. Leads technical AI safety at the UK AI Security Institute (AISI), the world\'s first government AI safety body. Sits at the critical intersection of frontier AI research and government policy.',
    manually_reviewed: true,
    review_notes: 'Leads frontier model safety evaluation at UK AISI. H-index ~48, ~98k citations.',
    geo: 'London',
    degree: 'PhD',
    field: 'AI Safety via Debate / Scalable Oversight',
  },
  {
    id: 'safety-010',
    label: 'Person',
    name: 'Dan Hendrycks',
    role: 'Director & Advisor',
    company: 'CAIS / xAI',
    composite_score: 8.4,
    founder_likelihood: 8.0,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/dan-hendrycks',
    github_handle: 'hendrycks',
    bio: 'Introduced the GELU activation function. Created the MMLU benchmark, now the de facto standard for measuring LLM capability and safety. Co-authored the AI extinction risk statement signed by Hinton, Bengio, and hundreds of leading researchers. Directs the Center for AI Safety (CAIS).',
    manually_reviewed: true,
    review_notes: 'Bridged academic ML safety and mainstream AI. CAIS extinction statement shaped public discourse. H-index ~55, ~64k citations.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'ML Safety / Robustness / AI Ethics',
  },
  {
    id: 'safety-011',
    label: 'Person',
    name: 'Jacob Steinhardt',
    role: 'Assistant Professor & Founder',
    company: 'UC Berkeley / Transluce',
    composite_score: 8.3,
    founder_likelihood: 8.0,
    pedigree_score: 9.0,
    trajectory_score: 8.0,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/jacob-steinhardt',
    github_handle: null,
    bio: 'Co-authored "Concrete Problems in AI Safety," one of the most influential AI safety papers. Co-created the MMLU benchmark. Founded Transluce, an interpretability research lab. Combines rigorous empirical ML research with safety-relevant theory at UC Berkeley.',
    manually_reviewed: true,
    review_notes: 'Outstanding academic. Transluce is a key infrastructure investment. H-index ~63, ~43k citations.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'Alignment / Robustness / Interpretability',
  },
  {
    id: 'safety-012',
    label: 'Person',
    name: 'Anca Dragan',
    role: 'Research Director',
    company: 'Google DeepMind / UC Berkeley',
    composite_score: 8.2,
    founder_likelihood: 7.0,
    pedigree_score: 9.0,
    trajectory_score: 9.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/anca-dragan',
    github_handle: null,
    bio: 'Pioneered Cooperative Inverse Reinforcement Learning (CIRL), a cornerstone framework for cooperative AI alignment. Leads AI Safety & Alignment for Gemini at Google DeepMind — making her research director for safety at the world\'s most compute-rich AI lab.',
    manually_reviewed: true,
    review_notes: 'CIRL is foundational for cooperative AI. Heads AI safety for Gemini at DeepMind. H-index ~76, ~31k citations.',
    geo: 'London',
    degree: 'PhD',
    field: 'Human-AI Alignment / Cooperative IRL / Reward Learning',
  },
  {
    id: 'safety-013',
    label: 'Person',
    name: 'Evan Hubinger',
    role: 'Alignment Researcher',
    company: 'Anthropic',
    composite_score: 7.9,
    founder_likelihood: 7.0,
    pedigree_score: 7.0,
    trajectory_score: 9.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: 'evhub',
    bio: 'Coined the concepts of mesa-optimization and inner alignment, now standard vocabulary in the field. Led landmark "sleeper agents" experiments and the alignment faking paper — two of the most significant empirical results in modern alignment research. Works at Anthropic.',
    manually_reviewed: true,
    review_notes: 'His conceptual frameworks are now standard vocabulary. Alignment faking paper is a field-definer. H-index ~23.',
    geo: 'San Francisco',
    degree: 'BS',
    field: 'Deceptive Alignment / Mesa-Optimization',
  },
  {
    id: 'safety-014',
    label: 'Person',
    name: 'Amanda Askell',
    role: 'Member of Technical Staff',
    company: 'Anthropic',
    composite_score: 7.8,
    founder_likelihood: 6.0,
    pedigree_score: 8.0,
    trajectory_score: 9.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Primary author of Claude\'s Constitution and AI character guidelines at Anthropic. Co-authored GPT-3 (77k+ citations). Named to TIME 100 AI 2024. A unique bridge between philosophy and practical alignment — Constitutional AI operationalizes safety principles at scale. ~192k total citations.',
    manually_reviewed: true,
    review_notes: 'Constitutional AI framework is a practical safety landmark. TIME 100 AI 2024. H-index ~54.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'Constitutional AI / AI Character / Ethics in LLMs',
  },
  {
    id: 'safety-015',
    label: 'Person',
    name: 'Percy Liang',
    role: 'Director, CRFM',
    company: 'Stanford / CRFM',
    composite_score: 7.8,
    founder_likelihood: 7.0,
    pedigree_score: 9.0,
    trajectory_score: 8.0,
    publication_score: 9.0,
    data_confidence: 9.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/percy-liang',
    github_handle: null,
    bio: 'Created the HELM benchmark, the gold standard for LLM safety evaluation, cited by AI labs, governments, and regulators worldwide. Directs the Center for Research on Foundation Models (CRFM). Co-authored the landmark Foundation Models report. H-index ~134, ~137k citations.',
    manually_reviewed: true,
    review_notes: 'HELM is cited by every major AI regulator. Extraordinarily high h-index for a safety researcher.',
    geo: 'Stanford',
    degree: 'PhD',
    field: 'Foundation Model Evaluation / Safety Benchmarks / HELM',
  },
  {
    id: 'safety-016',
    label: 'Person',
    name: 'Shane Legg',
    role: 'Co-Founder & Chief AGI Scientist',
    company: 'Google DeepMind',
    composite_score: 7.7,
    founder_likelihood: 10.0,
    pedigree_score: 10.0,
    trajectory_score: 8.0,
    publication_score: 6.0,
    data_confidence: 7.0,
    tier: 1,
    linkedin_url: 'https://linkedin.com/in/shane-legg',
    github_handle: null,
    bio: 'Co-founded DeepMind in 2010, selling it to Google for ~$500M. Authored the formal definition of machine superintelligence. Has been vocal about AI extinction risk since 2011. Leads AGI safety research at DeepMind, the most compute-rich AI safety team in the world.',
    manually_reviewed: true,
    review_notes: 'Quietly one of the most influential figures in AI safety. Vocal on extinction risk since 2011. H-index ~35.',
    geo: 'London',
    degree: 'PhD',
    field: 'AGI Safety / Long-term AI Risk',
  },
  {
    id: 'safety-017',
    label: 'Person',
    name: 'Nick Bostrom',
    role: 'Professor (formerly FHI Director)',
    company: 'University of Oxford',
    composite_score: 7.6,
    founder_likelihood: 8.0,
    pedigree_score: 9.0,
    trajectory_score: 7.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Author of Superintelligence (2014), which has 10,000+ citations and arguably launched the modern AI safety movement. Coined the concept of "existential risk" and founded the Future of Humanity Institute (FHI) at Oxford. FHI closed in 2024, but his intellectual influence remains immense.',
    manually_reviewed: true,
    review_notes: 'Superintelligence is arguably the most influential AI risk book ever. FHI closure diminished institutional reach. H-index ~63.',
    geo: 'Oxford',
    degree: 'PhD',
    field: 'Existential Risk / Superintelligence / AI Governance',
  },
  {
    id: 'safety-018',
    label: 'Person',
    name: 'Victoria Krakovna',
    role: 'Research Scientist',
    company: 'Google DeepMind',
    composite_score: 7.5,
    founder_likelihood: 7.0,
    pedigree_score: 8.0,
    trajectory_score: 8.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/victoria-krakovna',
    github_handle: null,
    bio: 'Co-authored AI Safety Gridworlds. Created the specification gaming database, a practical resource documenting reward hacking failures. Co-founded the Future of Life Institute (FLI). One of DeepMind\'s core AI safety researchers, working on AI control and safety evaluations.',
    manually_reviewed: true,
    review_notes: 'Spec-gaming database is a key practical safety resource. Co-founded FLI. H-index ~28.',
    geo: 'London',
    degree: 'PhD',
    field: 'Specification Gaming / AI Control / Safety Evaluations',
  },
  {
    id: 'safety-019',
    label: 'Person',
    name: 'Joelle Pineau',
    role: 'VP of AI Research',
    company: 'McGill / Meta FAIR',
    composite_score: 7.5,
    founder_likelihood: 6.0,
    pedigree_score: 8.0,
    trajectory_score: 8.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/joelle-pineau',
    github_handle: null,
    bio: 'Launched the ML Reproducibility Challenge, which has transformed research integrity standards across AI. Led Meta FAIR. AAAI Fellow and Fellow of the Royal Society of Canada. Her reproducibility work has had an outsized positive effect on AI research practices.',
    manually_reviewed: true,
    review_notes: 'Reproducibility work transformed AI research integrity. Led Meta FAIR. H-index ~84, ~41k citations.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'Responsible AI / Reproducibility / Reinforcement Learning',
  },
  {
    id: 'safety-020',
    label: 'Person',
    name: 'Finale Doshi-Velez',
    role: 'Professor',
    company: 'Harvard University',
    composite_score: 7.4,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 7.0,
    publication_score: 8.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/finale-doshi-velez',
    github_handle: null,
    bio: 'Leading academic voice on interpretability as a safety tool. Authored "Towards a Rigorous Science of Interpretable Machine Learning" and "Accountability of AI Under the Law." Focuses on ML in healthcare and AI fairness. Harvard SEAS professor.',
    manually_reviewed: true,
    review_notes: 'Policy-influential framing of interpretability as a safety requirement. H-index ~63, ~27k citations.',
    geo: 'Cambridge',
    degree: 'PhD',
    field: 'Interpretability / ML in Healthcare / AI Accountability',
  },
  {
    id: 'safety-021',
    label: 'Person',
    name: 'Dylan Hadfield-Menell',
    role: 'Assistant Professor',
    company: 'MIT CSAIL',
    composite_score: 7.3,
    founder_likelihood: 6.0,
    pedigree_score: 9.0,
    trajectory_score: 7.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-authored CIRL (Cooperative Inverse Reinforcement Learning), a cornerstone of cooperative AI alignment with 1,000+ citations. Leads the Algorithmic Alignment Group at MIT. Research focuses on societal oversight of AI systems and reward hacking.',
    manually_reviewed: true,
    review_notes: 'CIRL is foundational. Outstanding MIT pedigree. H-index ~38, ~7k citations.',
    geo: 'Cambridge',
    degree: 'PhD',
    field: 'AI Alignment / Cooperative IRL / Societal Oversight',
  },
  {
    id: 'safety-022',
    label: 'Person',
    name: 'Zachary Lipton',
    role: 'Associate Professor & Co-Founder',
    company: 'Carnegie Mellon / Abridge',
    composite_score: 7.3,
    founder_likelihood: 7.0,
    pedigree_score: 8.0,
    trajectory_score: 7.0,
    publication_score: 8.0,
    data_confidence: 9.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/zachary-lipton',
    github_handle: 'zackchase',
    bio: 'Author of "Mythos of Model Interpretability" (8,700+ citations), a critical counterweight to naive interpretability claims. Co-authored "Troubling Trends in ML Scholarship." Co-founded Abridge, an AI healthcare company. Forces rigor in safety-relevant ML claims.',
    manually_reviewed: true,
    review_notes: 'Critical voice on interpretability hype. Co-founded Abridge. H-index ~69, ~39k citations.',
    geo: 'Pittsburgh',
    degree: 'PhD',
    field: 'Interpretability Critique / Distribution Shift / ML & Healthcare',
  },
  {
    id: 'safety-023',
    label: 'Person',
    name: 'Arvind Narayanan',
    role: 'Professor',
    company: 'Princeton University',
    composite_score: 7.2,
    founder_likelihood: 5.0,
    pedigree_score: 8.0,
    trajectory_score: 8.0,
    publication_score: 8.0,
    data_confidence: 9.0,
    tier: 2,
    linkedin_url: null,
    github_handle: 'randomwalker',
    bio: 'Author of AI Snake Oil (2024), an authoritative technical critique of AI hype. Created the "21 Definitions of Fairness" tutorial. Co-authored the Fairness & ML textbook. His de-anonymization research changed privacy policy. Named to TIME 100 AI.',
    manually_reviewed: true,
    review_notes: 'De-anonymization work changed privacy policy. AI Snake Oil is a major public influence. H-index ~71, ~45k citations.',
    geo: 'Princeton',
    degree: 'PhD',
    field: 'AI Fairness / Privacy / De-anonymization / AI Hype Critique',
  },
  {
    id: 'safety-024',
    label: 'Person',
    name: 'Been Kim',
    role: 'Research Scientist',
    company: 'Google DeepMind',
    composite_score: 7.2,
    founder_likelihood: 5.0,
    pedigree_score: 8.0,
    trajectory_score: 8.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Invented TCAV (Testing with Concept Activation Vectors), a widely-deployed interpretability method used in Google production systems. Used AlphaZero to teach chess concepts to grandmasters, demonstrating a novel approach to human-AI collaboration and understanding.',
    manually_reviewed: true,
    review_notes: 'TCAV deployed at scale in Google systems. Uniquely practical and human-aligned interpretability. H-index ~42, ~18k citations.',
    geo: 'Mountain View',
    degree: 'PhD',
    field: 'Interpretability / Concept-Based Explanations (TCAV)',
  },
  {
    id: 'safety-025',
    label: 'Person',
    name: 'David Krueger',
    role: 'Assistant Professor',
    company: 'Université de Montréal / Mila',
    composite_score: 7.1,
    founder_likelihood: 7.0,
    pedigree_score: 7.0,
    trajectory_score: 8.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Initiated the CAIS extinction statement signed by Hinton, Bengio, and hundreds of researchers. Was research director at UK AISI at its founding. Co-authored a Science paper on AI governance. Bridges technical safety and governance at Mila.',
    manually_reviewed: true,
    review_notes: 'Key organizing role at UK AISI. Bridges technical safety and governance. H-index ~36, ~16k citations.',
    geo: 'Montreal',
    degree: 'PhD',
    field: 'Misgeneralization / Robustness / AI Governance',
  },
  {
    id: 'safety-026',
    label: 'Person',
    name: 'Scott Aaronson',
    role: 'Professor',
    company: 'UT Austin',
    composite_score: 7.0,
    founder_likelihood: 5.0,
    pedigree_score: 9.0,
    trajectory_score: 7.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Developed cryptographic watermarking for LLM outputs while at OpenAI — now deployed in ChatGPT at scale. Runs the influential Shtetl-Optimized blog on AI safety and quantum computing. His public writing on AI safety is influential well beyond academia.',
    manually_reviewed: true,
    review_notes: 'LLM watermarking deployed at scale. Public writing is influential beyond academia. H-index ~67, ~23k citations.',
    geo: 'Austin',
    degree: 'PhD',
    field: 'Watermarking LLMs / AI Foundations / Governance',
  },
  {
    id: 'safety-027',
    label: 'Person',
    name: 'Roger Grosse',
    role: 'Associate Professor & Researcher',
    company: 'University of Toronto / Anthropic',
    composite_score: 7.0,
    founder_likelihood: 6.0,
    pedigree_score: 8.0,
    trajectory_score: 8.0,
    publication_score: 7.0,
    data_confidence: 7.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Developed influence functions for ML attribution. Works on catastrophic failure probability estimation and safety cases at Anthropic. Rare combination of deep learning theory expertise and applied safety at a frontier lab. U of T professor and Anthropic affiliate.',
    manually_reviewed: true,
    review_notes: 'Rare DL theory + applied safety combination. Safety cases work is practically important. H-index ~45, ~15k citations.',
    geo: 'Toronto',
    degree: 'PhD',
    field: 'Training Data Attribution / Safety Cases / DL Theory',
  },
  {
    id: 'safety-028',
    label: 'Person',
    name: 'Timnit Gebru',
    role: 'Founder & Executive Director',
    company: 'DAIR Institute',
    composite_score: 6.9,
    founder_likelihood: 8.0,
    pedigree_score: 8.0,
    trajectory_score: 7.0,
    publication_score: 7.0,
    data_confidence: 8.0,
    tier: 2,
    linkedin_url: 'https://linkedin.com/in/timnit-gebru',
    github_handle: null,
    bio: 'Co-created Datasheets for Datasets, now a de facto industry standard. Led Gender Shades study exposing AI bias. Co-authored Stochastic Parrots. Her dismissal from Google catalyzed the AI ethics community globally. Founded DAIR. Named to TIME 100 AI.',
    manually_reviewed: true,
    review_notes: 'Google dismissal catalyzed AI ethics community. Datasheets is now a de facto standard. H-index ~28, ~37k citations.',
    geo: 'Oakland',
    degree: 'PhD',
    field: 'AI Ethics / Algorithmic Bias / Documentation',
  },
  {
    id: 'safety-029',
    label: 'Person',
    name: 'Solon Barocas',
    role: 'Senior Researcher & Professor',
    company: 'Microsoft Research / Cornell',
    composite_score: 6.8,
    founder_likelihood: 6.0,
    pedigree_score: 7.0,
    trajectory_score: 7.0,
    publication_score: 8.0,
    data_confidence: 9.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-authored the Fairness and ML textbook, the global academic standard. Wrote Big Data\'s Disparate Impact. Co-founded the ACM FAccT conference, now the premier venue for AI fairness, accountability, and transparency research. Cornell and MSR affiliate.',
    manually_reviewed: true,
    review_notes: 'Co-founding ACM FAccT was transformative. Fairness textbook is the global standard. H-index ~48, ~27k citations.',
    geo: 'New York',
    degree: 'PhD',
    field: 'Algorithmic Fairness / Accountability / Privacy',
  },
  {
    id: 'safety-030',
    label: 'Person',
    name: 'Eliezer Yudkowsky',
    role: 'Decision Theory Researcher',
    company: 'MIRI',
    composite_score: 6.7,
    founder_likelihood: 9.0,
    pedigree_score: 6.0,
    trajectory_score: 7.0,
    publication_score: 5.0,
    data_confidence: 7.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Founded the Machine Intelligence Research Institute (MIRI) in 2000 — the first dedicated AI safety lab. Formulated Coherent Extrapolated Volition (CEV). Author of Rationality: A-Z. Co-authored "If Anyone Builds It…" Disproportionate cultural influence despite modest formal publications. TIME 100 AI 2023.',
    manually_reviewed: true,
    review_notes: 'Disproportionately shaped safety field culturally. Modest publication record but outsized influence. H-index ~15.',
    geo: 'Berkeley',
    degree: 'Self-educated',
    field: 'AI Alignment Theory / Decision Theory / X-Risk',
  },
  {
    id: 'safety-031',
    label: 'Person',
    name: 'Nate Soares',
    role: 'Executive Director',
    company: 'MIRI',
    composite_score: 6.6,
    founder_likelihood: 7.0,
    pedigree_score: 6.0,
    trajectory_score: 7.0,
    publication_score: 5.0,
    data_confidence: 7.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Leads MIRI\'s technical agenda on agent foundations and corrigibility. Corrigibility & agent foundations framework is one of the most-cited theoretical contributions to alignment. Co-authored "If Anyone Builds It…" (2025). MIRI remains the oldest dedicated AI safety institution.',
    manually_reviewed: true,
    review_notes: 'Corrigibility framework is widely cited. Leads oldest dedicated safety institution. H-index ~15.',
    geo: 'Berkeley',
    degree: 'Self-educated',
    field: 'Agent Foundations / Corrigibility / Decision Theory',
  },
  {
    id: 'safety-032',
    label: 'Person',
    name: 'Thomas Dietterich',
    role: 'Professor Emeritus',
    company: 'Oregon State University',
    composite_score: 6.5,
    founder_likelihood: 4.0,
    pedigree_score: 8.0,
    trajectory_score: 6.0,
    publication_score: 9.0,
    data_confidence: 8.0,
    tier: 3,
    linkedin_url: 'https://linkedin.com/in/tom-dietterich',
    github_handle: null,
    bio: 'Gave the landmark AAAI Presidential Address on robust AI, framing the robustness research agenda. Pioneer of ensemble methods. A venerable elder statesman of AI safety, responsible for steering AAAI toward responsible AI research. H-index ~92, ~74k citations.',
    manually_reviewed: true,
    review_notes: 'AAAI presidential address framed robustness agenda. Elder statesman. H-index ~92, ~74k citations.',
    geo: 'Corvallis',
    degree: 'PhD',
    field: 'Robust AI / Anomaly Detection / Safe RL / Explainable AI',
  },
  {
    id: 'safety-033',
    label: 'Person',
    name: 'Rediet Abebe',
    role: 'Assistant Professor',
    company: 'UC Berkeley',
    composite_score: 6.4,
    founder_likelihood: 7.0,
    pedigree_score: 8.0,
    trajectory_score: 7.0,
    publication_score: 6.0,
    data_confidence: 8.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-founded Black in AI and MD4SG (Mechanism Design for Social Good), transforming the diversity of the AI safety and fairness field. Develops algorithmic frameworks for understanding inequality. MacArthur shortlist. UC Berkeley CS professor.',
    manually_reviewed: true,
    review_notes: 'Co-founding Black in AI transformed diversity of the safety field. MacArthur shortlist. H-index ~22.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'Algorithmic Justice / AI & Inequality / CS Theory',
  },
  {
    id: 'safety-034',
    label: 'Person',
    name: 'Kate Crawford',
    role: 'Research Professor',
    company: 'USC / Knowing Machines',
    composite_score: 6.3,
    founder_likelihood: 7.0,
    pedigree_score: 7.0,
    trajectory_score: 7.0,
    publication_score: 6.0,
    data_confidence: 7.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Author of Atlas of AI (FT Best Technology Book of 2021), the most influential critical AI book of the 2020s. Co-founded the AI Now Institute at NYU. Led the FATE group at Microsoft Research. Research focuses on the labor, power, and political economy of AI.',
    manually_reviewed: true,
    review_notes: 'Atlas of AI is the most influential critical AI book of the 2020s. Co-founded AI Now Institute. H-index ~21.',
    geo: 'Los Angeles',
    degree: 'PhD',
    field: 'AI Power & Labor / Surveillance / Political Economy',
  },
  {
    id: 'safety-035',
    label: 'Person',
    name: 'Jared Kaplan',
    role: 'Co-Founder',
    company: 'Anthropic',
    composite_score: 7.5,
    founder_likelihood: 9.0,
    pedigree_score: 9.0,
    trajectory_score: 8.0,
    publication_score: 8.0,
    data_confidence: 7.0,
    tier: 2,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-authored Neural Scaling Laws (2020), the paper foundational to all modern AI development. Co-authored GPT-3. Co-founded Anthropic. His scaling laws research is safety-relevant because it predicts emergent capabilities and informs when additional safety measures are needed.',
    manually_reviewed: true,
    review_notes: 'Scaling laws paper foundational for all modern AI development. Anthropic co-founder. H-index ~52, ~90k citations.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'Scaling Laws / Foundation Model Training / Alignment-at-Scale',
  },
  {
    id: 'safety-036',
    label: 'Person',
    name: 'Adam Gleave',
    role: 'Founder & CEO',
    company: 'FAR.AI',
    composite_score: 6.2,
    founder_likelihood: 8.0,
    pedigree_score: 8.0,
    trajectory_score: 7.0,
    publication_score: 6.0,
    data_confidence: 7.0,
    tier: 3,
    linkedin_url: 'https://linkedin.com/in/adam-gleave',
    github_handle: 'AdamGleave',
    bio: 'Founded FAR.AI, filling a critical niche in adversarial safety testing for AI. Pioneered adversarial policies research, revealing hidden behaviors in RL agents. Sits on the METR (Model Evaluation & Threat Research) board. A rising star in applied AI safety.',
    manually_reviewed: true,
    review_notes: 'FAR.AI fills a key niche in adversarial safety testing. Notable multi-board presence. H-index ~18.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'Adversarial Robustness / Hidden Behaviors / AI Security',
  },
  {
    id: 'safety-037',
    label: 'Person',
    name: 'Buck Shlegeris',
    role: 'CEO',
    company: 'Redwood Research',
    composite_score: 6.1,
    founder_likelihood: 8.0,
    pedigree_score: 6.0,
    trajectory_score: 7.0,
    publication_score: 5.0,
    data_confidence: 6.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Leads Redwood Research, one of the most respected independent safety labs. Authored the AI Control paper. Works on adversarial training for LM safety and tamper-proof safety mechanisms. Discovered the IOI circuit in neural networks.',
    manually_reviewed: true,
    review_notes: 'Redwood Research is one of the most respected independent safety labs. H-index ~10.',
    geo: 'Berkeley',
    degree: 'BS',
    field: 'AI Control / Adversarial Training / Tamper-Proof Safety',
  },
  {
    id: 'safety-038',
    label: 'Person',
    name: 'Jacob Hilton',
    role: 'Researcher',
    company: 'OpenAI',
    composite_score: 6.0,
    founder_likelihood: 5.0,
    pedigree_score: 8.0,
    trajectory_score: 7.0,
    publication_score: 6.0,
    data_confidence: 7.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-authored "Let\'s Verify Step by Step" (2,700+ citations), which introduced process reward models now deployed in OpenAI o1 reasoning models. Also worked on WebGPT and scalable oversight. A rising safety researcher at OpenAI with Cambridge pedigree.',
    manually_reviewed: true,
    review_notes: 'Process reward models deployed in OpenAI o1. Rising safety researcher. H-index ~18, ~3k citations.',
    geo: 'San Francisco',
    degree: 'PhD',
    field: 'Process Reward Models / Scalable Oversight / Verification',
  },
  {
    id: 'safety-039',
    label: 'Person',
    name: 'Owain Evans',
    role: 'Researcher',
    company: 'UC Berkeley / ARC',
    composite_score: 5.9,
    founder_likelihood: 6.0,
    pedigree_score: 8.0,
    trajectory_score: 6.0,
    publication_score: 6.0,
    data_confidence: 7.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Co-authored TruthfulQA (3,000+ citations), one of the most widely-used safety evaluation benchmarks globally. Conducts sycophancy research and works on scalable oversight at ARC and UC Berkeley. Oxford-trained with focus on agent evaluation and truthfulness.',
    manually_reviewed: true,
    review_notes: 'TruthfulQA is one of the most widely used safety benchmarks globally. H-index ~22, ~3.5k citations.',
    geo: 'Berkeley',
    degree: 'PhD',
    field: 'Sycophancy / Truthfulness / Scalable Oversight / Agent Eval',
  },
  {
    id: 'safety-040',
    label: 'Person',
    name: 'Jessica Taylor',
    role: 'Independent Researcher',
    company: 'Mercatoria / Independent',
    composite_score: 5.8,
    founder_likelihood: 6.0,
    pedigree_score: 7.0,
    trajectory_score: 6.0,
    publication_score: 5.0,
    data_confidence: 7.0,
    tier: 3,
    linkedin_url: null,
    github_handle: null,
    bio: 'Formalized logical uncertainty for AI systems at MIRI — foundational theoretical work. Made early contributions to decision theory and value learning that remain influential in the theoretical alignment community. Stanford MS. Now pursuing independent alignment research.',
    manually_reviewed: true,
    review_notes: 'Foundational theoretical work on logical uncertainty. Influential in early alignment community. H-index ~9.',
    geo: 'Berkeley',
    degree: 'MS',
    field: 'Decision Theory / Value Learning / Logical Uncertainty',
  },
]



// ── INSTITUTION NODES ─────────────────────────────────────────────────────

export const mockSafetyInstitutions = [
  { id: 'si-001', label: 'Institution', name: 'UC Berkeley',              type: 'university', country: 'USA',         world_rank: 4  },
  { id: 'si-002', label: 'Institution', name: 'Anthropic',                type: 'company',    country: 'USA',         world_rank: null },
  { id: 'si-003', label: 'Institution', name: 'OpenAI',                   type: 'company',    country: 'USA',         world_rank: null },
  { id: 'si-004', label: 'Institution', name: 'Google DeepMind',          type: 'company',    country: 'UK',          world_rank: null },
  { id: 'si-005', label: 'Institution', name: 'MIT',                      type: 'university', country: 'USA',         world_rank: 1  },
  { id: 'si-006', label: 'Institution', name: 'Stanford University',      type: 'university', country: 'USA',         world_rank: 3  },
  { id: 'si-007', label: 'Institution', name: 'University of Oxford',     type: 'university', country: 'UK',          world_rank: 5  },
  { id: 'si-008', label: 'Institution', name: 'Mila / U de Montréal',     type: 'university', country: 'Canada',      world_rank: null },
  { id: 'si-009', label: 'Institution', name: 'MIRI',                     type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-010', label: 'Institution', name: 'Harvard University',       type: 'university', country: 'USA',         world_rank: 2  },
  { id: 'si-011', label: 'Institution', name: 'Princeton University',     type: 'university', country: 'USA',         world_rank: 6  },
  { id: 'si-012', label: 'Institution', name: 'Carnegie Mellon University',type:'university', country: 'USA',         world_rank: 8  },
  { id: 'si-013', label: 'Institution', name: 'UK AI Security Institute', type: 'government', country: 'UK',          world_rank: null },
  { id: 'si-014', label: 'Institution', name: 'CAIS',                     type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-015', label: 'Institution', name: 'SSI',                      type: 'company',    country: 'USA',         world_rank: null },
  { id: 'si-016', label: 'Institution', name: 'DAIR Institute',           type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-017', label: 'Institution', name: 'Redwood Research',         type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-018', label: 'Institution', name: 'FAR.AI',                   type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-019', label: 'Institution', name: 'ARC',                      type: 'nonprofit',  country: 'USA',         world_rank: null },
  { id: 'si-020', label: 'Institution', name: 'McGill / Meta FAIR',       type: 'university', country: 'Canada',      world_rank: null },
]

// ── GEOGRAPHIC CLUSTER NODES ──────────────────────────────────────────────

export const mockSafetyGeo = [
  { id: 'sg-001', label: 'GeographicCluster', name: 'San Francisco',  country: 'USA'    },
  { id: 'sg-002', label: 'GeographicCluster', name: 'Berkeley',       country: 'USA'    },
  { id: 'sg-003', label: 'GeographicCluster', name: 'London',         country: 'UK'     },
  { id: 'sg-004', label: 'GeographicCluster', name: 'Montreal',       country: 'Canada' },
  { id: 'sg-005', label: 'GeographicCluster', name: 'Cambridge',      country: 'USA'    },
  { id: 'sg-006', label: 'GeographicCluster', name: 'Stanford',       country: 'USA'    },
  { id: 'sg-007', label: 'GeographicCluster', name: 'Oxford',         country: 'UK'     },
  { id: 'sg-008', label: 'GeographicCluster', name: 'Toronto',        country: 'Canada' },
  { id: 'sg-009', label: 'GeographicCluster', name: 'Pittsburgh',     country: 'USA'    },
  { id: 'sg-010', label: 'GeographicCluster', name: 'New York',       country: 'USA'    },
  { id: 'sg-011', label: 'GeographicCluster', name: 'Princeton',      country: 'USA'    },
  { id: 'sg-012', label: 'GeographicCluster', name: 'Austin',         country: 'USA'    },
  { id: 'sg-013', label: 'GeographicCluster', name: 'Mountain View',  country: 'USA'    },
  { id: 'sg-014', label: 'GeographicCluster', name: 'Palo Alto',      country: 'USA'    },
  { id: 'sg-015', label: 'GeographicCluster', name: 'Corvallis',      country: 'USA'    },
  { id: 'sg-016', label: 'GeographicCluster', name: 'Oakland',        country: 'USA'    },
  { id: 'sg-017', label: 'GeographicCluster', name: 'Los Angeles',    country: 'USA'    },
]

// ── EDGES ─────────────────────────────────────────────────────────────────
// EMPLOYED_AT
const safetyEmployedEdges = [
  { id: 'se-001', source: 'safety-001', target: 'si-001', type: 'EMPLOYED_AT',  label: 'CHAI Director' },
  { id: 'se-002', source: 'safety-002', target: 'si-008', type: 'EMPLOYED_AT',  label: 'Scientific Director' },
  { id: 'se-003', source: 'safety-003', target: 'si-015', type: 'EMPLOYED_AT',  label: 'Co-Founder & Chief Scientist' },
  { id: 'se-004', source: 'safety-004', target: 'si-002', type: 'EMPLOYED_AT',  label: 'CEO' },
  { id: 'se-005', source: 'safety-005', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Co-Founder' },
  { id: 'se-006', source: 'safety-006', target: 'si-019', type: 'EMPLOYED_AT',  label: 'Founder' },
  { id: 'se-007', source: 'safety-007', target: 'si-002', type: 'EMPLOYED_AT',  label: 'VP of Alignment' },
  { id: 'se-008', source: 'safety-008', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Interpretability Lead' },
  { id: 'se-009', source: 'safety-009', target: 'si-013', type: 'EMPLOYED_AT',  label: 'Technical Director' },
  { id: 'se-010', source: 'safety-010', target: 'si-014', type: 'EMPLOYED_AT',  label: 'Director' },
  { id: 'se-011', source: 'safety-011', target: 'si-001', type: 'EMPLOYED_AT',  label: 'Assistant Professor' },
  { id: 'se-012', source: 'safety-012', target: 'si-004', type: 'EMPLOYED_AT',  label: 'Research Director' },
  { id: 'se-013', source: 'safety-013', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Alignment Researcher' },
  { id: 'se-014', source: 'safety-014', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Member of Technical Staff' },
  { id: 'se-015', source: 'safety-015', target: 'si-006', type: 'EMPLOYED_AT',  label: 'CRFM Director' },
  { id: 'se-016', source: 'safety-016', target: 'si-004', type: 'EMPLOYED_AT',  label: 'Chief AGI Scientist' },
  { id: 'se-017', source: 'safety-017', target: 'si-007', type: 'EMPLOYED_AT',  label: 'Professor' },
  { id: 'se-018', source: 'safety-018', target: 'si-004', type: 'EMPLOYED_AT',  label: 'Research Scientist' },
  { id: 'se-019', source: 'safety-019', target: 'si-020', type: 'EMPLOYED_AT',  label: 'VP AI Research' },
  { id: 'se-020', source: 'safety-020', target: 'si-010', type: 'EMPLOYED_AT',  label: 'Professor' },
  { id: 'se-021', source: 'safety-021', target: 'si-005', type: 'EMPLOYED_AT',  label: 'Assistant Professor' },
  { id: 'se-022', source: 'safety-022', target: 'si-012', type: 'EMPLOYED_AT',  label: 'Associate Professor' },
  { id: 'se-023', source: 'safety-023', target: 'si-011', type: 'EMPLOYED_AT',  label: 'Professor' },
  { id: 'se-024', source: 'safety-024', target: 'si-004', type: 'EMPLOYED_AT',  label: 'Research Scientist' },
  { id: 'se-025', source: 'safety-025', target: 'si-008', type: 'EMPLOYED_AT',  label: 'Assistant Professor' },
  { id: 'se-026', source: 'safety-026', target: 'si-005', type: 'EMPLOYED_AT',  label: 'sabbatical → OpenAI' },
  { id: 'se-027', source: 'safety-027', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Affiliate Researcher' },
  { id: 'se-028', source: 'safety-028', target: 'si-016', type: 'EMPLOYED_AT',  label: 'Founder & Exec Director' },
  { id: 'se-029', source: 'safety-029', target: 'si-005', type: 'EMPLOYED_AT',  label: 'Senior Researcher' },
  { id: 'se-030', source: 'safety-030', target: 'si-009', type: 'EMPLOYED_AT',  label: 'Decision Theory Researcher' },
  { id: 'se-031', source: 'safety-031', target: 'si-009', type: 'EMPLOYED_AT',  label: 'Executive Director' },
  { id: 'se-033', source: 'safety-033', target: 'si-001', type: 'EMPLOYED_AT',  label: 'Assistant Professor' },
  { id: 'se-035', source: 'safety-035', target: 'si-002', type: 'EMPLOYED_AT',  label: 'Co-Founder' },
  { id: 'se-036', source: 'safety-036', target: 'si-018', type: 'EMPLOYED_AT',  label: 'Founder & CEO' },
  { id: 'se-037', source: 'safety-037', target: 'si-017', type: 'EMPLOYED_AT',  label: 'CEO' },
  { id: 'se-038', source: 'safety-038', target: 'si-003', type: 'EMPLOYED_AT',  label: 'Researcher' },
  { id: 'se-039', source: 'safety-039', target: 'si-001', type: 'EMPLOYED_AT',  label: 'Researcher' },
]

// ALUMNI_OF (PhD institution)
const safetyAlumniEdges = [
  { id: 'sa-001', source: 'safety-001', target: 'si-007', type: 'ALUMNI_OF', label: 'PhD — Oxford' },
  { id: 'sa-002', source: 'safety-002', target: 'si-010', type: 'ALUMNI_OF', label: 'PhD — McGill' },
  { id: 'sa-003', source: 'safety-003', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — U Toronto (via Hinton)' },
  { id: 'sa-004', source: 'safety-004', target: 'si-011', type: 'ALUMNI_OF', label: 'PhD — Princeton' },
  { id: 'sa-005', source: 'safety-005', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-006', source: 'safety-006', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-009', source: 'safety-009', target: 'si-006', type: 'ALUMNI_OF', label: 'PhD — Stanford' },
  { id: 'sa-010', source: 'safety-010', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-011', source: 'safety-011', target: 'si-006', type: 'ALUMNI_OF', label: 'PhD — Stanford' },
  { id: 'sa-012', source: 'safety-012', target: 'si-012', type: 'ALUMNI_OF', label: 'PhD — CMU' },
  { id: 'sa-014', source: 'safety-014', target: 'si-010', type: 'ALUMNI_OF', label: 'PhD — NYU' },
  { id: 'sa-015', source: 'safety-015', target: 'si-005', type: 'ALUMNI_OF', label: 'PhD — MIT' },
  { id: 'sa-018', source: 'safety-018', target: 'si-010', type: 'ALUMNI_OF', label: 'PhD — Harvard' },
  { id: 'sa-019', source: 'safety-019', target: 'si-012', type: 'ALUMNI_OF', label: 'PhD — CMU' },
  { id: 'sa-020', source: 'safety-020', target: 'si-005', type: 'ALUMNI_OF', label: 'PhD — MIT' },
  { id: 'sa-021', source: 'safety-021', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-023', source: 'safety-023', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UT Austin' },
  { id: 'sa-024', source: 'safety-024', target: 'si-005', type: 'ALUMNI_OF', label: 'PhD — MIT' },
  { id: 'sa-026', source: 'safety-026', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-027', source: 'safety-027', target: 'si-005', type: 'ALUMNI_OF', label: 'PhD — MIT' },
  { id: 'sa-028', source: 'safety-028', target: 'si-006', type: 'ALUMNI_OF', label: 'PhD — Stanford' },
  { id: 'sa-033', source: 'safety-033', target: 'si-010', type: 'ALUMNI_OF', label: 'PhD — Harvard' },
  { id: 'sa-035', source: 'safety-035', target: 'si-010', type: 'ALUMNI_OF', label: 'PhD — Johns Hopkins' },
  { id: 'sa-036', source: 'safety-036', target: 'si-001', type: 'ALUMNI_OF', label: 'PhD — UC Berkeley' },
  { id: 'sa-039', source: 'safety-039', target: 'si-007', type: 'ALUMNI_OF', label: 'PhD — Oxford' },
]

// LOCATED_IN (geo cluster)
const safetyGeoEdges = [
  { id: 'sl-001', source: 'safety-001', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-002', source: 'safety-002', target: 'sg-004', type: 'LOCATED_IN', label: 'Montreal' },
  { id: 'sl-003', source: 'safety-003', target: 'sg-014', type: 'LOCATED_IN', label: 'Palo Alto' },
  { id: 'sl-004', source: 'safety-004', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-005', source: 'safety-005', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-006', source: 'safety-006', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-007', source: 'safety-007', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-008', source: 'safety-008', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-009', source: 'safety-009', target: 'sg-003', type: 'LOCATED_IN', label: 'London' },
  { id: 'sl-010', source: 'safety-010', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-011', source: 'safety-011', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-012', source: 'safety-012', target: 'sg-003', type: 'LOCATED_IN', label: 'London' },
  { id: 'sl-013', source: 'safety-013', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-014', source: 'safety-014', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-015', source: 'safety-015', target: 'sg-006', type: 'LOCATED_IN', label: 'Stanford' },
  { id: 'sl-016', source: 'safety-016', target: 'sg-003', type: 'LOCATED_IN', label: 'London' },
  { id: 'sl-017', source: 'safety-017', target: 'sg-007', type: 'LOCATED_IN', label: 'Oxford' },
  { id: 'sl-018', source: 'safety-018', target: 'sg-003', type: 'LOCATED_IN', label: 'London' },
  { id: 'sl-019', source: 'safety-019', target: 'sg-004', type: 'LOCATED_IN', label: 'Montreal' },
  { id: 'sl-020', source: 'safety-020', target: 'sg-005', type: 'LOCATED_IN', label: 'Cambridge' },
  { id: 'sl-021', source: 'safety-021', target: 'sg-005', type: 'LOCATED_IN', label: 'Cambridge' },
  { id: 'sl-022', source: 'safety-022', target: 'sg-009', type: 'LOCATED_IN', label: 'Pittsburgh' },
  { id: 'sl-023', source: 'safety-023', target: 'sg-011', type: 'LOCATED_IN', label: 'Princeton' },
  { id: 'sl-024', source: 'safety-024', target: 'sg-013', type: 'LOCATED_IN', label: 'Mountain View' },
  { id: 'sl-025', source: 'safety-025', target: 'sg-004', type: 'LOCATED_IN', label: 'Montreal' },
  { id: 'sl-026', source: 'safety-026', target: 'sg-012', type: 'LOCATED_IN', label: 'Austin' },
  { id: 'sl-027', source: 'safety-027', target: 'sg-008', type: 'LOCATED_IN', label: 'Toronto' },
  { id: 'sl-028', source: 'safety-028', target: 'sg-016', type: 'LOCATED_IN', label: 'Oakland' },
  { id: 'sl-029', source: 'safety-029', target: 'sg-010', type: 'LOCATED_IN', label: 'New York' },
  { id: 'sl-030', source: 'safety-030', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-031', source: 'safety-031', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-033', source: 'safety-033', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-034', source: 'safety-034', target: 'sg-017', type: 'LOCATED_IN', label: 'Los Angeles' },
  { id: 'sl-035', source: 'safety-035', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-036', source: 'safety-036', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-037', source: 'safety-037', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-038', source: 'safety-038', target: 'sg-001', type: 'LOCATED_IN', label: 'San Francisco' },
  { id: 'sl-039', source: 'safety-039', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
  { id: 'sl-040', source: 'safety-040', target: 'sg-002', type: 'LOCATED_IN', label: 'Berkeley' },
]

// CO_AUTHORED_WITH (key collaborations)
const safetyCoAuthorEdges = [
  { id: 'sc-001', source: 'safety-004', target: 'safety-005', type: 'CO_AUTHORED_WITH', label: 'InstructGPT / RLHF (2022)' },
  { id: 'sc-002', source: 'safety-004', target: 'safety-006', type: 'CO_AUTHORED_WITH', label: 'RLHF co-invention (2017)' },
  { id: 'sc-003', source: 'safety-004', target: 'safety-035', type: 'CO_AUTHORED_WITH', label: 'GPT-3 / Anthropic founding' },
  { id: 'sc-004', source: 'safety-003', target: 'safety-004', type: 'CO_AUTHORED_WITH', label: 'Co-invented RLHF' },
  { id: 'sc-005', source: 'safety-007', target: 'safety-006', type: 'CO_AUTHORED_WITH', label: 'Superalignment (2023)' },
  { id: 'sc-006', source: 'safety-010', target: 'safety-011', type: 'CO_AUTHORED_WITH', label: 'MMLU benchmark (2020)' },
  { id: 'sc-007', source: 'safety-001', target: 'safety-012', type: 'CO_AUTHORED_WITH', label: 'CIRL / cooperative AI' },
  { id: 'sc-008', source: 'safety-021', target: 'safety-012', type: 'CO_AUTHORED_WITH', label: 'CIRL paper (2016)' },
  { id: 'sc-009', source: 'safety-002', target: 'safety-025', type: 'CO_AUTHORED_WITH', label: 'CAIS extinction statement' },
  { id: 'sc-010', source: 'safety-008', target: 'safety-013', type: 'CO_AUTHORED_WITH', label: 'Interpretability / circuits' },
  { id: 'sc-011', source: 'safety-014', target: 'safety-004', type: 'CO_AUTHORED_WITH', label: 'Constitutional AI (2022)' },
  { id: 'sc-012', source: 'safety-030', target: 'safety-031', type: 'CO_AUTHORED_WITH', label: 'MIRI alignment agenda' },
  { id: 'sc-013', source: 'safety-018', target: 'safety-016', type: 'CO_AUTHORED_WITH', label: 'Future of Life Institute' },
  { id: 'sc-014', source: 'safety-006', target: 'safety-009', type: 'CO_AUTHORED_WITH', label: 'AI Safety via Debate (2018)' },
  { id: 'sc-015', source: 'safety-038', target: 'safety-007', type: 'CO_AUTHORED_WITH', label: 'Scalable oversight / WebGPT' },
]

// ADVISED_BY
const safetyAdvisedEdges = [
  { id: 'sv-001', source: 'safety-006', target: 'safety-001', type: 'ADVISED_BY', label: 'PhD advisor' },
  { id: 'sv-002', source: 'safety-021', target: 'safety-001', type: 'ADVISED_BY', label: 'PhD advisor' },
  { id: 'sv-003', source: 'safety-011', target: 'safety-015', type: 'ADVISED_BY', label: 'PhD co-advisor' },
  { id: 'sv-004', source: 'safety-036', target: 'safety-011', type: 'ADVISED_BY', label: 'PhD advisor' },
  { id: 'sv-005', source: 'safety-005', target: 'safety-001', type: 'ADVISED_BY', label: 'academic lineage' },
]

export const mockSafetyEdges = [
  ...safetyEmployedEdges,
  ...safetyAlumniEdges,
  ...safetyGeoEdges,
  ...safetyCoAuthorEdges,
  ...safetyAdvisedEdges,
]

export const mockSafetyNodes = [
  ...mockSafetyPersonNodes,
  ...mockSafetyInstitutions,
  ...mockSafetyGeo,
]
